#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
site_dir="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${site_dir}/.." && pwd)"
dashboard_dir="${repo_root}/dashboard/app"
site_dist_dir="${site_dir}/dist"
dashboard_dist_dir="${dashboard_dir}/dist"
npm_cache_dir="${repo_root}/.netlify/cache/npm"
pnpm_store_dir="${repo_root}/.netlify/cache/pnpm-store"
corepack_home_dir="${repo_root}/.netlify/cache/corepack"

require_env() {
  local name="$1"
  local value="${!name:-}"

  if [ -z "${value}" ]; then
    echo "Missing required environment variable: ${name}" >&2
    exit 1
  fi

  printf '%s' "${value%/}"
}

require_ops_credential() {
  local name="$1"
  local value="${!name:-}"

  if [ -z "${value}" ]; then
    echo "Missing required environment variable: ${name}" >&2
    exit 1
  fi

  printf '%s' "${value}"
}

console_fe_origin="$(require_env CONSOLE_FE_ORIGIN)"
console_api_origin="$(require_env CONSOLE_API_ORIGIN)"
ops_username="$(require_ops_credential CONSOLE_OPS_BASIC_AUTH_USERNAME)"
ops_password="$(require_ops_credential CONSOLE_OPS_BASIC_AUTH_PASSWORD)"

if [ "${#ops_username}" -gt 64 ] || [[ ! "${ops_username}" =~ ^[A-Za-z0-9._~-]+$ ]]; then
  echo "CONSOLE_OPS_BASIC_AUTH_USERNAME must use 1-64 URL-safe ASCII characters" >&2
  exit 1
fi
if [ "${#ops_password}" -lt 24 ] || [ "${#ops_password}" -gt 512 ] || [[ ! "${ops_password}" =~ ^[A-Za-z0-9_-]+$ ]]; then
  echo "CONSOLE_OPS_BASIC_AUTH_PASSWORD must use 24-512 base64url characters" >&2
  exit 1
fi

mkdir -p "${npm_cache_dir}" "${pnpm_store_dir}" "${corepack_home_dir}"

export ASTRO_TELEMETRY_DISABLED=1
export CI=true
export COREPACK_HOME="${corepack_home_dir}"

echo "==> Building site"
rm -rf "${site_dist_dir}"
if [ ! -x "${site_dir}/node_modules/.bin/astro" ]; then
  echo "==> Installing site dependencies"
  npm --prefix "${site_dir}" ci --cache "${npm_cache_dir}"
fi
npm --prefix "${site_dir}" run build:netlify

echo "==> Installing dashboard dependencies"
(
  cd "${dashboard_dir}"
  corepack pnpm --store-dir "${pnpm_store_dir}" install --frozen-lockfile
)

echo "==> Building dashboard"
rm -rf "${dashboard_dist_dir}"
(
  cd "${dashboard_dir}"
  corepack pnpm build
)

echo "==> Merging dashboard into site output"
mkdir -p "${site_dist_dir}/your-memory"
cp -R "${dashboard_dist_dir}/." "${site_dist_dir}/your-memory/"
rm -f "${site_dist_dir}/your-memory/_redirects"

echo "==> Writing console redirects"
cat > "${site_dist_dir}/_redirects" <<REDIRECTS
# Generated by site/scripts/netlify-build.sh.
# Configure CONSOLE_FE_ORIGIN and CONSOLE_API_ORIGIN per deploy context.
# Ops pages are owned by Console FE and protected at the Netlify edge.
/console/ops        /console/ops/                                  301!
/console/ops/api/*  ${console_api_origin}/ops/api/:splat         200!
/console/ops/*      ${console_fe_origin}/console/ops/:splat      200!
/console/api/*      ${console_api_origin}/api/:splat             200!
/console/auth/*     ${console_api_origin}/auth/:splat            200!
/console/admin-api.md  ${console_fe_origin}/console/admin-api.md  200
/console/spaces/api-guide/import-api-keys.md  ${console_fe_origin}/console/spaces/api-guide/import-api-keys.md  200
/console/assets/*  ${console_fe_origin}/console/assets/:splat   200
/console/favicon.svg  ${console_fe_origin}/console/favicon.svg  200
/console           ${console_fe_origin}/console/index.html      200
/console/          ${console_fe_origin}/console/index.html      200
/console/*         ${console_fe_origin}/console/index.html      200
REDIRECTS

cat > "${site_dist_dir}/_headers" <<HEADERS
# Generated by site/scripts/netlify-build.sh.
/console/ops/*
  Basic-Auth: ${ops_username}:${ops_password}
  Cache-Control: private, no-store
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
HEADERS
