export const PIXEL_FARM_GENERATED_LAYERS = [
  {
    id: "soil",
    label: "0 Soil",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      ".......########.........................",
      ".......#########........................",
      "...#...############################.....",
      "...#...#############################....",
      "...#..##############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".......#############################....",
      ".................##################.....",
      "........................................",
    ],
    overrides: {
      "0:10": { sourceId: "soil", frame: 1 },
      "0:11": { sourceId: "soil", frame: 1 },
      "0:12": { sourceId: "soil", frame: 1 },
      "0:13": { sourceId: "soil", frame: 1 },
      "0:14": { sourceId: "soil", frame: 2 },
      "0:7": { sourceId: "soil", frame: 0 },
      "0:8": { sourceId: "soil", frame: 1 },
      "0:9": { sourceId: "soil", frame: 1 },
      "1:14": { sourceId: "soil", frame: 27 },
      "1:15": { sourceId: "soil", frame: 2 },
      "1:7": { sourceId: "soil", frame: 11 },
      "10:35": { sourceId: "soil", frame: 13 },
      "10:5": { sourceId: "soil", frame: 11 },
      "11:35": { sourceId: "soil", frame: 13 },
      "11:5": { sourceId: "soil", frame: 11 },
      "12:35": { sourceId: "soil", frame: 13 },
      "12:5": { sourceId: "soil", frame: 11 },
      "13:35": { sourceId: "soil", frame: 13 },
      "13:5": { sourceId: "soil", frame: 11 },
      "14:35": { sourceId: "soil", frame: 13 },
      "14:5": { sourceId: "soil", frame: 11 },
      "15:35": { sourceId: "soil", frame: 13 },
      "15:5": { sourceId: "soil", frame: 11 },
      "16:35": { sourceId: "soil", frame: 13 },
      "16:5": { sourceId: "soil", frame: 11 },
      "17:35": { sourceId: "soil", frame: 13 },
      "17:5": { sourceId: "soil", frame: 11 },
      "18:35": { sourceId: "soil", frame: 13 },
      "18:5": { sourceId: "soil", frame: 11 },
      "19:35": { sourceId: "soil", frame: 13 },
      "19:5": { sourceId: "soil", frame: 11 },
      "2:15": { sourceId: "soil", frame: 27 },
      "2:16": { sourceId: "soil", frame: 1 },
      "2:17": { sourceId: "soil", frame: 1 },
      "2:18": { sourceId: "soil", frame: 1 },
      "2:19": { sourceId: "soil", frame: 1 },
      "2:20": { sourceId: "soil", frame: 1 },
      "2:21": { sourceId: "soil", frame: 1 },
      "2:22": { sourceId: "soil", frame: 1 },
      "2:23": { sourceId: "soil", frame: 1 },
      "2:24": { sourceId: "soil", frame: 1 },
      "2:25": { sourceId: "soil", frame: 1 },
      "2:26": { sourceId: "soil", frame: 1 },
      "2:27": { sourceId: "soil", frame: 1 },
      "2:28": { sourceId: "soil", frame: 1 },
      "2:29": { sourceId: "soil", frame: 1 },
      "2:3": { sourceId: "soil", frame: 3 },
      "2:30": { sourceId: "soil", frame: 1 },
      "2:31": { sourceId: "soil", frame: 1 },
      "2:32": { sourceId: "soil", frame: 1 },
      "2:33": { sourceId: "soil", frame: 1 },
      "2:34": { sourceId: "soil", frame: 2 },
      "2:7": { sourceId: "soil", frame: 11 },
      "20:35": { sourceId: "soil", frame: 13 },
      "20:5": { sourceId: "soil", frame: 11 },
      "21:35": { sourceId: "soil", frame: 13 },
      "21:5": { sourceId: "soil", frame: 11 },
      "22:35": { sourceId: "soil", frame: 13 },
      "22:5": { sourceId: "soil", frame: 22 },
      "22:6": { sourceId: "soil", frame: 23 },
      "22:7": { sourceId: "soil", frame: 17 },
      "23:10": { sourceId: "soil", frame: 23 },
      "23:11": { sourceId: "soil", frame: 23 },
      "23:12": { sourceId: "soil", frame: 23 },
      "23:13": { sourceId: "soil", frame: 23 },
      "23:14": { sourceId: "soil", frame: 23 },
      "23:15": { sourceId: "soil", frame: 23 },
      "23:16": { sourceId: "soil", frame: 23 },
      "23:17": { sourceId: "soil", frame: 17 },
      "23:34": { sourceId: "soil", frame: 16 },
      "23:35": { sourceId: "soil", frame: 24 },
      "23:7": { sourceId: "soil", frame: 22 },
      "23:8": { sourceId: "soil", frame: 23 },
      "23:9": { sourceId: "soil", frame: 23 },
      "24:17": { sourceId: "soil", frame: 22 },
      "24:18": { sourceId: "soil", frame: 23 },
      "24:19": { sourceId: "soil", frame: 23 },
      "24:20": { sourceId: "soil", frame: 23 },
      "24:21": { sourceId: "soil", frame: 23 },
      "24:22": { sourceId: "soil", frame: 23 },
      "24:23": { sourceId: "soil", frame: 23 },
      "24:24": { sourceId: "soil", frame: 23 },
      "24:25": { sourceId: "soil", frame: 23 },
      "24:26": { sourceId: "soil", frame: 23 },
      "24:27": { sourceId: "soil", frame: 23 },
      "24:28": { sourceId: "soil", frame: 23 },
      "24:29": { sourceId: "soil", frame: 23 },
      "24:30": { sourceId: "soil", frame: 23 },
      "24:31": { sourceId: "soil", frame: 23 },
      "24:32": { sourceId: "soil", frame: 23 },
      "24:33": { sourceId: "soil", frame: 23 },
      "24:34": { sourceId: "soil", frame: 24 },
      "3:3": { sourceId: "soil", frame: 14 },
      "3:34": { sourceId: "soil", frame: 27 },
      "3:35": { sourceId: "soil", frame: 2 },
      "3:7": { sourceId: "soil", frame: 11 },
      "4:3": { sourceId: "soil", frame: 25 },
      "4:35": { sourceId: "soil", frame: 13 },
      "4:6": { sourceId: "soil", frame: 0 },
      "4:7": { sourceId: "soil", frame: 28 },
      "5:35": { sourceId: "soil", frame: 13 },
      "5:5": { sourceId: "soil", frame: 0 },
      "5:6": { sourceId: "soil", frame: 28 },
      "6:35": { sourceId: "soil", frame: 13 },
      "6:5": { sourceId: "soil", frame: 11 },
      "7:35": { sourceId: "soil", frame: 13 },
      "7:5": { sourceId: "soil", frame: 11 },
      "8:35": { sourceId: "soil", frame: 13 },
      "8:5": { sourceId: "soil", frame: 11 },
      "9:35": { sourceId: "soil", frame: 13 },
      "9:5": { sourceId: "soil", frame: 11 },
    },
  },
  {
    id: "grass-light",
    label: "1 Grass",
    baseTile: { sourceId: "grassLight", frame: 12 },
    mask: [
      ".......########.........................",
      ".......#########........................",
      ".......############################.....",
      ".......#############################....",
      "......##############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".##..###############################....",
      ".##..###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".......#############################....",
      ".................##################.....",
      "........................................",
    ],
    overrides: {
      "0:10": { sourceId: "grassLight", frame: 1 },
      "0:11": { sourceId: "grassLight", frame: 1 },
      "0:12": { sourceId: "grassLight", frame: 1 },
      "0:13": { sourceId: "grassLight", frame: 1 },
      "0:14": { sourceId: "grassLight", frame: 2 },
      "0:7": { sourceId: "grassLight", frame: 0 },
      "0:8": { sourceId: "grassLight", frame: 1 },
      "0:9": { sourceId: "grassLight", frame: 1 },
      "1:14": { sourceId: "grassLight", frame: 27 },
      "1:15": { sourceId: "grassLight", frame: 2 },
      "1:7": { sourceId: "grassLight", frame: 11 },
      "10:35": { sourceId: "grassLight", frame: 13 },
      "10:5": { sourceId: "grassLight", frame: 11 },
      "11:1": { sourceId: "grassLight", frame: 0 },
      "11:2": { sourceId: "grassLight", frame: 2 },
      "11:35": { sourceId: "grassLight", frame: 13 },
      "11:5": { sourceId: "grassLight", frame: 11 },
      "12:1": { sourceId: "grassLight", frame: 22 },
      "12:2": { sourceId: "grassLight", frame: 24 },
      "12:35": { sourceId: "grassLight", frame: 13 },
      "12:5": { sourceId: "grassLight", frame: 11 },
      "13:35": { sourceId: "grassLight", frame: 13 },
      "13:5": { sourceId: "grassLight", frame: 11 },
      "14:35": { sourceId: "grassLight", frame: 13 },
      "14:5": { sourceId: "grassLight", frame: 11 },
      "15:35": { sourceId: "grassLight", frame: 13 },
      "15:5": { sourceId: "grassLight", frame: 11 },
      "16:35": { sourceId: "grassLight", frame: 13 },
      "16:5": { sourceId: "grassLight", frame: 11 },
      "17:35": { sourceId: "grassLight", frame: 13 },
      "17:5": { sourceId: "grassLight", frame: 11 },
      "18:35": { sourceId: "grassLight", frame: 13 },
      "18:5": { sourceId: "grassLight", frame: 11 },
      "19:35": { sourceId: "grassLight", frame: 13 },
      "19:5": { sourceId: "grassLight", frame: 11 },
      "2:15": { sourceId: "grassLight", frame: 27 },
      "2:16": { sourceId: "grassLight", frame: 1 },
      "2:17": { sourceId: "grassLight", frame: 1 },
      "2:18": { sourceId: "grassLight", frame: 1 },
      "2:19": { sourceId: "grassLight", frame: 1 },
      "2:20": { sourceId: "grassLight", frame: 1 },
      "2:21": { sourceId: "grassLight", frame: 1 },
      "2:22": { sourceId: "grassLight", frame: 1 },
      "2:23": { sourceId: "grassLight", frame: 1 },
      "2:24": { sourceId: "grassLight", frame: 1 },
      "2:25": { sourceId: "grassLight", frame: 1 },
      "2:26": { sourceId: "grassLight", frame: 1 },
      "2:27": { sourceId: "grassLight", frame: 1 },
      "2:28": { sourceId: "grassLight", frame: 1 },
      "2:29": { sourceId: "grassLight", frame: 1 },
      "2:30": { sourceId: "grassLight", frame: 1 },
      "2:31": { sourceId: "grassLight", frame: 1 },
      "2:32": { sourceId: "grassLight", frame: 1 },
      "2:33": { sourceId: "grassLight", frame: 1 },
      "2:34": { sourceId: "grassLight", frame: 2 },
      "2:7": { sourceId: "grassLight", frame: 11 },
      "20:35": { sourceId: "grassLight", frame: 13 },
      "20:5": { sourceId: "grassLight", frame: 11 },
      "21:12": { sourceId: "grassLight", frame: 69 },
      "21:35": { sourceId: "grassLight", frame: 13 },
      "21:5": { sourceId: "grassLight", frame: 11 },
      "22:35": { sourceId: "grassLight", frame: 13 },
      "22:5": { sourceId: "grassLight", frame: 22 },
      "22:6": { sourceId: "grassLight", frame: 23 },
      "22:7": { sourceId: "grassLight", frame: 17 },
      "23:10": { sourceId: "grassLight", frame: 23 },
      "23:11": { sourceId: "grassLight", frame: 23 },
      "23:12": { sourceId: "grassLight", frame: 23 },
      "23:13": { sourceId: "grassLight", frame: 23 },
      "23:14": { sourceId: "grassLight", frame: 23 },
      "23:15": { sourceId: "grassLight", frame: 23 },
      "23:16": { sourceId: "grassLight", frame: 23 },
      "23:17": { sourceId: "grassLight", frame: 17 },
      "23:34": { sourceId: "grassLight", frame: 16 },
      "23:35": { sourceId: "grassLight", frame: 24 },
      "23:7": { sourceId: "grassLight", frame: 22 },
      "23:8": { sourceId: "grassLight", frame: 23 },
      "23:9": { sourceId: "grassLight", frame: 23 },
      "24:17": { sourceId: "grassLight", frame: 22 },
      "24:18": { sourceId: "grassLight", frame: 23 },
      "24:19": { sourceId: "grassLight", frame: 23 },
      "24:20": { sourceId: "grassLight", frame: 23 },
      "24:21": { sourceId: "grassLight", frame: 23 },
      "24:22": { sourceId: "grassLight", frame: 23 },
      "24:23": { sourceId: "grassLight", frame: 23 },
      "24:24": { sourceId: "grassLight", frame: 23 },
      "24:25": { sourceId: "grassLight", frame: 23 },
      "24:26": { sourceId: "grassLight", frame: 23 },
      "24:27": { sourceId: "grassLight", frame: 23 },
      "24:28": { sourceId: "grassLight", frame: 23 },
      "24:29": { sourceId: "grassLight", frame: 23 },
      "24:30": { sourceId: "grassLight", frame: 23 },
      "24:31": { sourceId: "grassLight", frame: 23 },
      "24:32": { sourceId: "grassLight", frame: 23 },
      "24:33": { sourceId: "grassLight", frame: 23 },
      "24:34": { sourceId: "grassLight", frame: 24 },
      "3:34": { sourceId: "grassLight", frame: 27 },
      "3:35": { sourceId: "grassLight", frame: 2 },
      "3:7": { sourceId: "grassLight", frame: 11 },
      "4:35": { sourceId: "grassLight", frame: 13 },
      "4:6": { sourceId: "grassLight", frame: 0 },
      "4:7": { sourceId: "grassLight", frame: 28 },
      "5:35": { sourceId: "grassLight", frame: 13 },
      "5:5": { sourceId: "grassLight", frame: 0 },
      "5:6": { sourceId: "grassLight", frame: 28 },
      "6:35": { sourceId: "grassLight", frame: 13 },
      "6:5": { sourceId: "grassLight", frame: 11 },
      "7:35": { sourceId: "grassLight", frame: 13 },
      "7:5": { sourceId: "grassLight", frame: 11 },
      "8:35": { sourceId: "grassLight", frame: 13 },
      "8:5": { sourceId: "grassLight", frame: 11 },
      "9:35": { sourceId: "grassLight", frame: 13 },
      "9:5": { sourceId: "grassLight", frame: 11 },
    },
  },
  {
    id: "bush",
    label: "2 Bush",
    baseTile: { sourceId: "bush", frame: 0 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "......#..............................#..",
      "....................................#...",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      ".....................................#..",
      "......................................#.",
      ".....................................#..",
      "........................................",
      "....................................##..",
      "........................................",
      "......#.................................",
      "...#....................................",
      "........................................",
    ],
    overrides: {
      "17:37": { sourceId: "waterObjects", frame: 0 },
      "18:38": { sourceId: "waterObjects", frame: 1 },
      "19:37": { sourceId: "waterObjects", frame: 3 },
      "21:36": { sourceId: "waterObjects", frame: 4 },
      "21:37": { sourceId: "waterObjects", frame: 5 },
      "23:6": { sourceId: "waterObjects", frame: 9 },
      "24:3": { sourceId: "waterObjects", frame: 1 },
      "3:37": { sourceId: "waterObjects", frame: 0 },
      "3:6": { sourceId: "waterObjects", frame: 11 },
      "4:36": { sourceId: "waterObjects", frame: 3 },
    },
  },
  {
    id: "layer-5",
    label: "2-1 grassHill",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "........................##########......",
      "........................###########.....",
      "........................###########.....",
      "........................###########.....",
      "........................###########.....",
      "........................###########.....",
      "..........................#########.....",
      "..........................#########.....",
      "...............................##.......",
      "...............................##.......",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
    ],
    overrides: {
      "10:26": { sourceId: "grassHill", frame: 22 },
      "10:27": { sourceId: "grassHill", frame: 23 },
      "10:28": { sourceId: "grassHill", frame: 23 },
      "10:29": { sourceId: "grassHill", frame: 23 },
      "10:30": { sourceId: "grassHill", frame: 23 },
      "10:31": { sourceId: "grassHillSlopes", frame: 4 },
      "10:32": { sourceId: "grassHillSlopes", frame: 5 },
      "10:33": { sourceId: "grassHill", frame: 23 },
      "10:34": { sourceId: "grassHill", frame: 24 },
      "11:31": { sourceId: "grassHillSlopes", frame: 10 },
      "11:32": { sourceId: "grassHillSlopes", frame: 11 },
      "12:31": { sourceId: "grassHillSlopes", frame: 16 },
      "12:32": { sourceId: "grassHillSlopes", frame: 17 },
      "3:24": { sourceId: "grassHill", frame: 0 },
      "3:25": { sourceId: "grassHill", frame: 1 },
      "3:26": { sourceId: "grassHill", frame: 1 },
      "3:27": { sourceId: "grassHill", frame: 1 },
      "3:28": { sourceId: "grassHill", frame: 1 },
      "3:29": { sourceId: "grassHill", frame: 1 },
      "3:30": { sourceId: "grassHill", frame: 1 },
      "3:31": { sourceId: "grassHill", frame: 1 },
      "3:32": { sourceId: "grassHill", frame: 1 },
      "3:33": { sourceId: "grassHill", frame: 2 },
      "4:24": { sourceId: "grassHill", frame: 11 },
      "4:25": { sourceId: "grassHill", frame: 55 },
      "4:26": { sourceId: "grassHill", frame: 12 },
      "4:27": { sourceId: "grassHill", frame: 12 },
      "4:28": { sourceId: "grassHill", frame: 12 },
      "4:29": { sourceId: "grassHill", frame: 12 },
      "4:30": { sourceId: "grassHill", frame: 12 },
      "4:31": { sourceId: "grassHill", frame: 12 },
      "4:32": { sourceId: "grassHill", frame: 12 },
      "4:33": { sourceId: "grassHill", frame: 27 },
      "4:34": { sourceId: "grassHill", frame: 2 },
      "5:24": { sourceId: "grassHill", frame: 11 },
      "5:25": { sourceId: "grassHill", frame: 12 },
      "5:26": { sourceId: "grassHill", frame: 12 },
      "5:27": { sourceId: "grassHill", frame: 12 },
      "5:28": { sourceId: "grassHill", frame: 12 },
      "5:29": { sourceId: "grassHill", frame: 12 },
      "5:30": { sourceId: "grassHill", frame: 12 },
      "5:31": { sourceId: "grassHill", frame: 12 },
      "5:32": { sourceId: "grassHill", frame: 60 },
      "5:33": { sourceId: "grassHill", frame: 12 },
      "5:34": { sourceId: "grassHill", frame: 13 },
      "6:24": { sourceId: "grassHill", frame: 11 },
      "6:25": { sourceId: "grassLight", frame: 66 },
      "6:26": { sourceId: "grassHill", frame: 12 },
      "6:27": { sourceId: "grassHill", frame: 12 },
      "6:28": { sourceId: "grassHill", frame: 12 },
      "6:29": { sourceId: "grassHill", frame: 12 },
      "6:30": { sourceId: "grassHill", frame: 12 },
      "6:31": { sourceId: "grassHill", frame: 12 },
      "6:32": { sourceId: "grassHill", frame: 12 },
      "6:33": { sourceId: "grassHill", frame: 12 },
      "6:34": { sourceId: "grassHill", frame: 13 },
      "7:24": { sourceId: "grassHill", frame: 11 },
      "7:25": { sourceId: "grassHill", frame: 57 },
      "7:26": { sourceId: "grassLight", frame: 66 },
      "7:27": { sourceId: "grassHill", frame: 12 },
      "7:28": { sourceId: "grassHill", frame: 12 },
      "7:29": { sourceId: "grassHill", frame: 12 },
      "7:30": { sourceId: "grassHill", frame: 12 },
      "7:31": { sourceId: "grassHill", frame: 12 },
      "7:32": { sourceId: "grassHill", frame: 12 },
      "7:33": { sourceId: "grassHill", frame: 12 },
      "7:34": { sourceId: "grassHill", frame: 13 },
      "8:24": { sourceId: "grassHill", frame: 22 },
      "8:25": { sourceId: "grassHill", frame: 23 },
      "8:26": { sourceId: "grassHill", frame: 17 },
      "8:27": { sourceId: "grassHill", frame: 12 },
      "8:28": { sourceId: "grassHill", frame: 12 },
      "8:29": { sourceId: "grassHill", frame: 12 },
      "8:30": { sourceId: "grassHill", frame: 12 },
      "8:31": { sourceId: "grassHill", frame: 12 },
      "8:32": { sourceId: "grassHill", frame: 12 },
      "8:33": { sourceId: "grassLight", frame: 66 },
      "8:34": { sourceId: "grassHill", frame: 13 },
      "9:26": { sourceId: "grassHill", frame: 11 },
      "9:27": { sourceId: "grassHill", frame: 12 },
      "9:28": { sourceId: "grassHill", frame: 12 },
      "9:29": { sourceId: "grassHill", frame: 12 },
      "9:30": { sourceId: "grassHill", frame: 12 },
      "9:31": { sourceId: "grassHill", frame: 12 },
      "9:32": { sourceId: "grassHill", frame: 70 },
      "9:33": { sourceId: "grassHill", frame: 12 },
      "9:34": { sourceId: "grassHill", frame: 13 },
    },
  },
  {
    id: "layer-6",
    label: "2-2 tiled",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "..........###...........................",
      "..........###...........................",
      ".........####...........................",
      ".........####...........................",
      ".........####...........................",
      ".........####...........................",
      ".........####...........................",
      ".................######.................",
      "...............########.................",
      "...............#############............",
      "...............#############...###......",
      "...............#############..####......",
      "................###########...####......",
      "..............................###.......",
      "........................................",
      "....................########............",
      "...................#########..####......",
      "..................##########..####......",
      "..................##########..####......",
      "........................................",
      "........................................",
      "........................................",
    ],
    overrides: {
      "10:10": { sourceId: "tilledDirtWide", frame: 72 },
      "10:11": { sourceId: "tilledDirtWide", frame: 72 },
      "10:12": { sourceId: "tilledDirtWide", frame: 24 },
      "10:9": { sourceId: "tilledDirtWide", frame: 22 },
      "11:17": { sourceId: "tilledDirtWide", frame: 0 },
      "11:18": { sourceId: "tilledDirtWide", frame: 60 },
      "11:19": { sourceId: "tilledDirtWide", frame: 62 },
      "11:20": { sourceId: "tilledDirtWide", frame: 62 },
      "11:21": { sourceId: "tilledDirtWide", frame: 1 },
      "11:22": { sourceId: "tilledDirtWide", frame: 2 },
      "12:15": { sourceId: "tilledDirtWide", frame: 0 },
      "12:16": { sourceId: "tilledDirtWide", frame: 1 },
      "12:17": { sourceId: "tilledDirtWide", frame: 28 },
      "12:18": { sourceId: "tilledDirtWide", frame: 12 },
      "12:19": { sourceId: "tilledDirtWide", frame: 66 },
      "12:20": { sourceId: "tilledDirtWide", frame: 12 },
      "12:21": { sourceId: "tilledDirtWide", frame: 67 },
      "12:22": { sourceId: "tilledDirtWide", frame: 13 },
      "13:15": { sourceId: "tilledDirtWide", frame: 74 },
      "13:16": { sourceId: "tilledDirtWide", frame: 66 },
      "13:17": { sourceId: "tilledDirtWide", frame: 12 },
      "13:18": { sourceId: "tilledDirtWide", frame: 12 },
      "13:19": { sourceId: "tilledDirtWide", frame: 12 },
      "13:20": { sourceId: "tilledDirtWide", frame: 67 },
      "13:21": { sourceId: "tilledDirtWide", frame: 66 },
      "13:22": { sourceId: "tilledDirtWide", frame: 27 },
      "13:23": { sourceId: "tilledDirtWide", frame: 1 },
      "13:24": { sourceId: "tilledDirtWide", frame: 62 },
      "13:25": { sourceId: "tilledDirtWide", frame: 62 },
      "13:26": { sourceId: "tilledDirtWide", frame: 1 },
      "13:27": { sourceId: "tilledDirtWide", frame: 2 },
      "14:15": { sourceId: "tilledDirtWide", frame: 74 },
      "14:16": { sourceId: "tilledDirtWide", frame: 66 },
      "14:17": { sourceId: "tilledDirtWide", frame: 66 },
      "14:18": { sourceId: "tilledDirtWide", frame: 12 },
      "14:19": { sourceId: "tilledDirtWide", frame: 12 },
      "14:20": { sourceId: "tilledDirtWide", frame: 12 },
      "14:21": { sourceId: "tilledDirtWide", frame: 12 },
      "14:22": { sourceId: "tilledDirtWide", frame: 12 },
      "14:23": { sourceId: "tilledDirtWide", frame: 12 },
      "14:24": { sourceId: "tilledDirtWide", frame: 12 },
      "14:25": { sourceId: "tilledDirtWide", frame: 12 },
      "14:26": { sourceId: "tilledDirtWide", frame: 66 },
      "14:27": { sourceId: "tilledDirtWide", frame: 75 },
      "14:31": { sourceId: "tilledDirtWide", frame: 0 },
      "14:32": { sourceId: "tilledDirtWide", frame: 60 },
      "14:33": { sourceId: "tilledDirtWide", frame: 2 },
      "15:15": { sourceId: "tilledDirtWide", frame: 22 },
      "15:16": { sourceId: "tilledDirtWide", frame: 17 },
      "15:17": { sourceId: "tilledDirtWide", frame: 12 },
      "15:18": { sourceId: "tilledDirtWide", frame: 67 },
      "15:19": { sourceId: "tilledDirtWide", frame: 12 },
      "15:20": { sourceId: "tilledDirtWide", frame: 66 },
      "15:21": { sourceId: "tilledDirtWide", frame: 12 },
      "15:22": { sourceId: "tilledDirtWide", frame: 12 },
      "15:23": { sourceId: "tilledDirtWide", frame: 66 },
      "15:24": { sourceId: "tilledDirtWide", frame: 66 },
      "15:25": { sourceId: "tilledDirtWide", frame: 12 },
      "15:26": { sourceId: "tilledDirtWide", frame: 16 },
      "15:27": { sourceId: "tilledDirtWide", frame: 24 },
      "15:30": { sourceId: "tilledDirtWide", frame: 0 },
      "15:31": { sourceId: "tilledDirtWide", frame: 28 },
      "15:32": { sourceId: "tilledDirtWide", frame: 57 },
      "15:33": { sourceId: "tilledDirtWide", frame: 13 },
      "16:16": { sourceId: "tilledDirtWide", frame: 22 },
      "16:17": { sourceId: "tilledDirtWide", frame: 71 },
      "16:18": { sourceId: "tilledDirtWide", frame: 23 },
      "16:19": { sourceId: "tilledDirtWide", frame: 23 },
      "16:20": { sourceId: "tilledDirtWide", frame: 71 },
      "16:21": { sourceId: "tilledDirtWide", frame: 72 },
      "16:22": { sourceId: "tilledDirtWide", frame: 72 },
      "16:23": { sourceId: "tilledDirtWide", frame: 23 },
      "16:24": { sourceId: "tilledDirtWide", frame: 23 },
      "16:25": { sourceId: "tilledDirtWide", frame: 23 },
      "16:26": { sourceId: "tilledDirtWide", frame: 24 },
      "16:30": { sourceId: "tilledDirtWide", frame: 74 },
      "16:31": { sourceId: "tilledDirtWide", frame: 66 },
      "16:32": { sourceId: "tilledDirtWide", frame: 16 },
      "16:33": { sourceId: "tilledDirtWide", frame: 24 },
      "17:30": { sourceId: "tilledDirtWide", frame: 22 },
      "17:31": { sourceId: "tilledDirtWide", frame: 72 },
      "17:32": { sourceId: "tilledDirtWide", frame: 24 },
      "19:20": { sourceId: "tilledDirtWide", frame: 0 },
      "19:21": { sourceId: "tilledDirtWide", frame: 60 },
      "19:22": { sourceId: "tilledDirtWide", frame: 61 },
      "19:23": { sourceId: "tilledDirtWide", frame: 62 },
      "19:24": { sourceId: "tilledDirtWide", frame: 1 },
      "19:25": { sourceId: "tilledDirtWide", frame: 1 },
      "19:26": { sourceId: "tilledDirtWide", frame: 62 },
      "19:27": { sourceId: "tilledDirtWide", frame: 2 },
      "20:19": { sourceId: "tilledDirtWide", frame: 0 },
      "20:20": { sourceId: "tilledDirtWide", frame: 28 },
      "20:21": { sourceId: "tilledDirtWide", frame: 66 },
      "20:22": { sourceId: "tilledDirtWide", frame: 12 },
      "20:23": { sourceId: "tilledDirtWide", frame: 12 },
      "20:24": { sourceId: "tilledDirtWide", frame: 12 },
      "20:25": { sourceId: "tilledDirtWide", frame: 66 },
      "20:26": { sourceId: "tilledDirtWide", frame: 67 },
      "20:27": { sourceId: "tilledDirtWide", frame: 64 },
      "20:30": { sourceId: "tilledDirtWide", frame: 0 },
      "20:31": { sourceId: "tilledDirtWide", frame: 1 },
      "20:32": { sourceId: "tilledDirtWide", frame: 62 },
      "20:33": { sourceId: "tilledDirtWide", frame: 2 },
      "21:18": { sourceId: "tilledDirtWide", frame: 0 },
      "21:19": { sourceId: "tilledDirtWide", frame: 28 },
      "21:20": { sourceId: "tilledDirtWide", frame: 66 },
      "21:21": { sourceId: "tilledDirtWide", frame: 12 },
      "21:22": { sourceId: "tilledDirtWide", frame: 67 },
      "21:23": { sourceId: "tilledDirtWide", frame: 12 },
      "21:24": { sourceId: "tilledDirtWide", frame: 66 },
      "21:25": { sourceId: "tilledDirtWide", frame: 12 },
      "21:26": { sourceId: "tilledDirtWide", frame: 66 },
      "21:27": { sourceId: "tilledDirtWide", frame: 75 },
      "21:30": { sourceId: "tilledDirtWide", frame: 74 },
      "21:31": { sourceId: "tilledDirtWide", frame: 66 },
      "21:32": { sourceId: "tilledDirtWide", frame: 66 },
      "21:33": { sourceId: "tilledDirtWide", frame: 64 },
      "22:18": { sourceId: "tilledDirtWide", frame: 22 },
      "22:19": { sourceId: "tilledDirtWide", frame: 23 },
      "22:20": { sourceId: "tilledDirtWide", frame: 23 },
      "22:21": { sourceId: "tilledDirtWide", frame: 72 },
      "22:22": { sourceId: "tilledDirtWide", frame: 72 },
      "22:23": { sourceId: "tilledDirtWide", frame: 71 },
      "22:24": { sourceId: "tilledDirtWide", frame: 23 },
      "22:25": { sourceId: "tilledDirtWide", frame: 23 },
      "22:26": { sourceId: "tilledDirtWide", frame: 23 },
      "22:27": { sourceId: "tilledDirtWide", frame: 24 },
      "22:30": { sourceId: "tilledDirtWide", frame: 22 },
      "22:31": { sourceId: "tilledDirtWide", frame: 72 },
      "22:32": { sourceId: "tilledDirtWide", frame: 23 },
      "22:33": { sourceId: "tilledDirtWide", frame: 24 },
      "4:10": { sourceId: "tilledDirtWide", frame: 0 },
      "4:11": { sourceId: "tilledDirtWide", frame: 60 },
      "4:12": { sourceId: "tilledDirtWide", frame: 2 },
      "5:10": { sourceId: "tilledDirtWide", frame: 11 },
      "5:11": { sourceId: "tilledDirtWide", frame: 12 },
      "5:12": { sourceId: "tilledDirtWide", frame: 13 },
      "6:10": { sourceId: "tilledDirtWide", frame: 28 },
      "6:11": { sourceId: "tilledDirtWide", frame: 12 },
      "6:12": { sourceId: "tilledDirtWide", frame: 64 },
      "6:9": { sourceId: "tilledDirtWide", frame: 0 },
      "7:10": { sourceId: "tiledDirt", frame: 66 },
      "7:11": { sourceId: "tilledDirtWide", frame: 57 },
      "7:12": { sourceId: "tilledDirtWide", frame: 64 },
      "7:9": { sourceId: "tilledDirtWide", frame: 74 },
      "8:10": { sourceId: "tilledDirtWide", frame: 12 },
      "8:11": { sourceId: "tiledDirt", frame: 66 },
      "8:12": { sourceId: "tilledDirtWide", frame: 13 },
      "8:9": { sourceId: "tilledDirtWide", frame: 74 },
      "9:10": { sourceId: "tiledDirt", frame: 66 },
      "9:11": { sourceId: "tilledDirtWide", frame: 12 },
      "9:12": { sourceId: "tilledDirtWide", frame: 13 },
      "9:9": { sourceId: "tilledDirtWide", frame: 11 },
    },
  },
  {
    id: "layer-7",
    label: "2-3 house",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      "........................................",
      "........................................",
      "..............................###.......",
      "..............................###.......",
      "..............................###.......",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
    ],
    overrides: {
      "2:30": { sourceId: "chickenHouses", frame: 198 },
      "2:31": { sourceId: "chickenHouses", frame: 199 },
      "2:32": { sourceId: "chickenHouses", frame: 200 },
      "3:30": { sourceId: "chickenHouses", frame: 222 },
      "3:31": { sourceId: "chickenHouses", frame: 223 },
      "3:32": { sourceId: "chickenHouses", frame: 224 },
      "4:30": { sourceId: "chickenHouses", frame: 246 },
      "4:31": { sourceId: "chickenHouses", frame: 247 },
      "4:32": { sourceId: "chickenHouses", frame: 248 },
    },
  },
  {
    id: "objects",
    label: "3 Objects",
    baseTile: { sourceId: "bush", frame: 0 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
    ],
    overrides: {},
  },
] as const;

export const PIXEL_FARM_GENERATED_OBJECTS = [
  {
    id: "object-1",
    layerId: "objects",
    sourceId: "signs",
    frame: 15,
    row: 14,
    column: 30,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-2",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 17,
    column: 33,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-3",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 24,
    row: 17,
    column: 32,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-4",
    layerId: "objects",
    sourceId: "fences",
    frame: 0,
    row: 15,
    column: 34,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-5",
    layerId: "objects",
    sourceId: "fences",
    frame: 16,
    row: 16,
    column: 34,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-6",
    layerId: "objects",
    sourceId: "fences",
    frame: 0,
    row: 21,
    column: 34,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-7",
    layerId: "objects",
    sourceId: "fences",
    frame: 16,
    row: 22,
    column: 34,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-8",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 23,
    column: 31,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-9",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 23,
    column: 33,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-10",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 23,
    column: 32,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-11",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 23,
    column: 19,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-12",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 23,
    column: 20,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-13",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 23,
    column: 21,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-14",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 23,
    column: 24,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-15",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 23,
    column: 25,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-16",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 23,
    column: 26,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-17",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 3,
    column: 26,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-18",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 3,
    column: 27,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-19",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 3,
    column: 28,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-23",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 40,
    row: 4,
    column: 30,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-24",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 41,
    row: 4,
    column: 33,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-22",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 17,
    row: 3,
    column: 25,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-25",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 3,
    column: 29,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-26",
    layerId: "objects",
    sourceId: "fences",
    frame: 17,
    row: 21,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-27",
    layerId: "objects",
    sourceId: "fences",
    frame: 3,
    row: 21,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-28",
    layerId: "objects",
    sourceId: "fences",
    frame: 17,
    row: 22,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-29",
    layerId: "objects",
    sourceId: "fences",
    frame: 20,
    row: 22,
    column: 9,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-30",
    layerId: "objects",
    sourceId: "fences",
    frame: 23,
    row: 22,
    column: 10,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-31",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 22,
    column: 11,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-32",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 22,
    column: 12,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-33",
    layerId: "objects",
    sourceId: "fences",
    frame: 19,
    row: 22,
    column: 13,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-34",
    layerId: "objects",
    sourceId: "fences",
    frame: 0,
    row: 21,
    column: 13,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-35",
    layerId: "objects",
    sourceId: "fences",
    frame: 8,
    row: 20,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-36",
    layerId: "objects",
    sourceId: "fences",
    frame: 8,
    row: 19,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-37",
    layerId: "objects",
    sourceId: "fences",
    frame: 8,
    row: 18,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-38",
    layerId: "objects",
    sourceId: "fences",
    frame: 1,
    row: 17,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-39",
    layerId: "objects",
    sourceId: "fences",
    frame: 4,
    row: 17,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-40",
    layerId: "objects",
    sourceId: "fences",
    frame: 7,
    row: 17,
    column: 9,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-41",
    layerId: "objects",
    sourceId: "fences",
    frame: 2,
    row: 17,
    column: 10,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-42",
    layerId: "objects",
    sourceId: "fences",
    frame: 20,
    row: 17,
    column: 11,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-43",
    layerId: "objects",
    sourceId: "fences",
    frame: 23,
    row: 17,
    column: 12,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-44",
    layerId: "objects",
    sourceId: "fences",
    frame: 3,
    row: 17,
    column: 13,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-45",
    layerId: "objects",
    sourceId: "fences",
    frame: 16,
    row: 18,
    column: 13,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-46",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 9,
    row: 20,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-47",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 9,
    row: 18,
    column: 12,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-48",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 10,
    row: 21,
    column: 9,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-49",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 3,
    row: 21,
    column: 14,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-50",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 6,
    row: 22,
    column: 15,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-51",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 7,
    row: 22,
    column: 16,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-52",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 10,
    row: 0,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-53",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 11,
    row: 0,
    column: 9,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-54",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 22,
    row: 1,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-55",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 23,
    row: 1,
    column: 9,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-56",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 34,
    row: 2,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-57",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 35,
    row: 2,
    column: 9,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-58",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 15,
    row: 2,
    column: 10,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-59",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 14,
    row: 3,
    column: 8,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-60",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 46,
    row: 1,
    column: 10,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-63",
    layerId: "objects",
    sourceId: "waterWell",
    frame: 0,
    row: 3,
    column: 21,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-64",
    layerId: "objects",
    sourceId: "waterWell",
    frame: 1,
    row: 3,
    column: 22,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-65",
    layerId: "objects",
    sourceId: "waterWell",
    frame: 2,
    row: 4,
    column: 21,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-66",
    layerId: "objects",
    sourceId: "waterWell",
    frame: 3,
    row: 4,
    column: 22,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-67",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 1,
    row: 10,
    column: 6,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-68",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 2,
    row: 10,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-69",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 4,
    row: 11,
    column: 6,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-70",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 5,
    row: 11,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-73",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 26,
    row: 21,
    column: 6,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-74",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 22,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-75",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 40,
    row: 23,
    column: 30,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-76",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 41,
    row: 22,
    column: 29,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-77",
    layerId: "objects",
    sourceId: "workStation",
    frame: 0,
    row: 8,
    column: 27,
    footprint: { rows: 1, columns: 1 },
    walkable: true,
  },
  {
    id: "object-78",
    layerId: "objects",
    sourceId: "workStation",
    frame: 1,
    row: 8,
    column: 28,
    footprint: { rows: 1, columns: 1 },
    walkable: true,
  },
  {
    id: "object-79",
    layerId: "objects",
    sourceId: "workStation",
    frame: 2,
    row: 9,
    column: 27,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-80",
    layerId: "objects",
    sourceId: "workStation",
    frame: 3,
    row: 9,
    column: 28,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-81",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 12,
    row: 2,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-82",
    layerId: "objects",
    sourceId: "stonePath",
    frame: 5,
    row: 12,
    column: 6,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-83",
    layerId: "objects",
    sourceId: "stonePath",
    frame: 6,
    row: 12,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-84",
    layerId: "objects",
    sourceId: "stonePath",
    frame: 9,
    row: 13,
    column: 6,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
  {
    id: "object-85",
    layerId: "objects",
    sourceId: "stonePath",
    frame: 10,
    row: 13,
    column: 7,
    footprint: { rows: 1, columns: 1 },
    walkable: false,
  },
] as const;
