export const PIXEL_FARM_GENERATED_LAYERS = [
  {
    id: "soil",
    label: "0 Soil",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      ".......########.........................",
      ".......#########........................",
      "...#...############################.....",
      "...#...#############################....",
      "...#..##############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".......#############################....",
      ".................##################.....",
      "........................................",
    ],
    overrides: {
      "0:10": { sourceId: "soil", frame: 1 },
      "0:11": { sourceId: "soil", frame: 1 },
      "0:12": { sourceId: "soil", frame: 1 },
      "0:13": { sourceId: "soil", frame: 1 },
      "0:14": { sourceId: "soil", frame: 2 },
      "0:7": { sourceId: "soil", frame: 0 },
      "0:8": { sourceId: "soil", frame: 1 },
      "0:9": { sourceId: "soil", frame: 1 },
      "1:14": { sourceId: "soil", frame: 27 },
      "1:15": { sourceId: "soil", frame: 2 },
      "1:7": { sourceId: "soil", frame: 11 },
      "10:35": { sourceId: "soil", frame: 13 },
      "10:5": { sourceId: "soil", frame: 11 },
      "11:35": { sourceId: "soil", frame: 13 },
      "11:5": { sourceId: "soil", frame: 11 },
      "12:35": { sourceId: "soil", frame: 13 },
      "12:5": { sourceId: "soil", frame: 11 },
      "13:35": { sourceId: "soil", frame: 13 },
      "13:5": { sourceId: "soil", frame: 11 },
      "14:35": { sourceId: "soil", frame: 13 },
      "14:5": { sourceId: "soil", frame: 11 },
      "15:35": { sourceId: "soil", frame: 13 },
      "15:5": { sourceId: "soil", frame: 11 },
      "16:35": { sourceId: "soil", frame: 13 },
      "16:5": { sourceId: "soil", frame: 11 },
      "17:35": { sourceId: "soil", frame: 13 },
      "17:5": { sourceId: "soil", frame: 11 },
      "18:35": { sourceId: "soil", frame: 13 },
      "18:5": { sourceId: "soil", frame: 11 },
      "19:35": { sourceId: "soil", frame: 13 },
      "19:5": { sourceId: "soil", frame: 11 },
      "2:15": { sourceId: "soil", frame: 27 },
      "2:16": { sourceId: "soil", frame: 1 },
      "2:17": { sourceId: "soil", frame: 1 },
      "2:18": { sourceId: "soil", frame: 1 },
      "2:19": { sourceId: "soil", frame: 1 },
      "2:20": { sourceId: "soil", frame: 1 },
      "2:21": { sourceId: "soil", frame: 1 },
      "2:22": { sourceId: "soil", frame: 1 },
      "2:23": { sourceId: "soil", frame: 1 },
      "2:24": { sourceId: "soil", frame: 1 },
      "2:25": { sourceId: "soil", frame: 1 },
      "2:26": { sourceId: "soil", frame: 1 },
      "2:27": { sourceId: "soil", frame: 1 },
      "2:28": { sourceId: "soil", frame: 1 },
      "2:29": { sourceId: "soil", frame: 1 },
      "2:3": { sourceId: "soil", frame: 3 },
      "2:30": { sourceId: "soil", frame: 1 },
      "2:31": { sourceId: "soil", frame: 1 },
      "2:32": { sourceId: "soil", frame: 1 },
      "2:33": { sourceId: "soil", frame: 1 },
      "2:34": { sourceId: "soil", frame: 2 },
      "2:7": { sourceId: "soil", frame: 11 },
      "20:35": { sourceId: "soil", frame: 13 },
      "20:5": { sourceId: "soil", frame: 11 },
      "21:35": { sourceId: "soil", frame: 13 },
      "21:5": { sourceId: "soil", frame: 11 },
      "22:35": { sourceId: "soil", frame: 13 },
      "22:5": { sourceId: "soil", frame: 22 },
      "22:6": { sourceId: "soil", frame: 23 },
      "22:7": { sourceId: "soil", frame: 17 },
      "23:10": { sourceId: "soil", frame: 23 },
      "23:11": { sourceId: "soil", frame: 23 },
      "23:12": { sourceId: "soil", frame: 23 },
      "23:13": { sourceId: "soil", frame: 23 },
      "23:14": { sourceId: "soil", frame: 23 },
      "23:15": { sourceId: "soil", frame: 23 },
      "23:16": { sourceId: "soil", frame: 23 },
      "23:17": { sourceId: "soil", frame: 17 },
      "23:34": { sourceId: "soil", frame: 16 },
      "23:35": { sourceId: "soil", frame: 24 },
      "23:7": { sourceId: "soil", frame: 22 },
      "23:8": { sourceId: "soil", frame: 23 },
      "23:9": { sourceId: "soil", frame: 23 },
      "24:17": { sourceId: "soil", frame: 22 },
      "24:18": { sourceId: "soil", frame: 23 },
      "24:19": { sourceId: "soil", frame: 23 },
      "24:20": { sourceId: "soil", frame: 23 },
      "24:21": { sourceId: "soil", frame: 23 },
      "24:22": { sourceId: "soil", frame: 23 },
      "24:23": { sourceId: "soil", frame: 23 },
      "24:24": { sourceId: "soil", frame: 23 },
      "24:25": { sourceId: "soil", frame: 23 },
      "24:26": { sourceId: "soil", frame: 23 },
      "24:27": { sourceId: "soil", frame: 23 },
      "24:28": { sourceId: "soil", frame: 23 },
      "24:29": { sourceId: "soil", frame: 23 },
      "24:30": { sourceId: "soil", frame: 23 },
      "24:31": { sourceId: "soil", frame: 23 },
      "24:32": { sourceId: "soil", frame: 23 },
      "24:33": { sourceId: "soil", frame: 23 },
      "24:34": { sourceId: "soil", frame: 24 },
      "3:3": { sourceId: "soil", frame: 14 },
      "3:34": { sourceId: "soil", frame: 27 },
      "3:35": { sourceId: "soil", frame: 2 },
      "3:7": { sourceId: "soil", frame: 11 },
      "4:3": { sourceId: "soil", frame: 25 },
      "4:35": { sourceId: "soil", frame: 13 },
      "4:6": { sourceId: "soil", frame: 0 },
      "4:7": { sourceId: "soil", frame: 28 },
      "5:35": { sourceId: "soil", frame: 13 },
      "5:5": { sourceId: "soil", frame: 0 },
      "5:6": { sourceId: "soil", frame: 28 },
      "6:35": { sourceId: "soil", frame: 13 },
      "6:5": { sourceId: "soil", frame: 11 },
      "7:35": { sourceId: "soil", frame: 13 },
      "7:5": { sourceId: "soil", frame: 11 },
      "8:35": { sourceId: "soil", frame: 13 },
      "8:5": { sourceId: "soil", frame: 11 },
      "9:35": { sourceId: "soil", frame: 13 },
      "9:5": { sourceId: "soil", frame: 11 },
    },
  },
  {
    id: "grass-light",
    label: "1 Grass",
    baseTile: { sourceId: "grassLight", frame: 12 },
    mask: [
      ".......########.........................",
      ".......#########........................",
      ".......############################.....",
      ".......#############################....",
      "......##############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".##..###############################....",
      ".##..###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".......#############################....",
      ".................##################.....",
      "........................................",
    ],
    overrides: {
      "0:10": { sourceId: "grassLight", frame: 1 },
      "0:11": { sourceId: "grassLight", frame: 1 },
      "0:12": { sourceId: "grassLight", frame: 1 },
      "0:13": { sourceId: "grassLight", frame: 1 },
      "0:14": { sourceId: "grassLight", frame: 2 },
      "0:7": { sourceId: "grassLight", frame: 0 },
      "0:8": { sourceId: "grassLight", frame: 1 },
      "0:9": { sourceId: "grassLight", frame: 1 },
      "1:14": { sourceId: "grassLight", frame: 27 },
      "1:15": { sourceId: "grassLight", frame: 2 },
      "1:7": { sourceId: "grassLight", frame: 11 },
      "10:35": { sourceId: "grassLight", frame: 13 },
      "10:5": { sourceId: "grassLight", frame: 11 },
      "11:1": { sourceId: "grassLight", frame: 0 },
      "11:2": { sourceId: "grassLight", frame: 2 },
      "11:35": { sourceId: "grassLight", frame: 13 },
      "11:5": { sourceId: "grassLight", frame: 11 },
      "12:1": { sourceId: "grassLight", frame: 22 },
      "12:2": { sourceId: "grassLight", frame: 24 },
      "12:35": { sourceId: "grassLight", frame: 13 },
      "12:5": { sourceId: "grassLight", frame: 11 },
      "13:35": { sourceId: "grassLight", frame: 13 },
      "13:5": { sourceId: "grassLight", frame: 11 },
      "14:35": { sourceId: "grassLight", frame: 13 },
      "14:5": { sourceId: "grassLight", frame: 11 },
      "15:35": { sourceId: "grassLight", frame: 13 },
      "15:5": { sourceId: "grassLight", frame: 11 },
      "16:35": { sourceId: "grassLight", frame: 13 },
      "16:5": { sourceId: "grassLight", frame: 11 },
      "17:35": { sourceId: "grassLight", frame: 13 },
      "17:5": { sourceId: "grassLight", frame: 11 },
      "18:35": { sourceId: "grassLight", frame: 13 },
      "18:5": { sourceId: "grassLight", frame: 11 },
      "19:35": { sourceId: "grassLight", frame: 13 },
      "19:5": { sourceId: "grassLight", frame: 11 },
      "2:15": { sourceId: "grassLight", frame: 27 },
      "2:16": { sourceId: "grassLight", frame: 1 },
      "2:17": { sourceId: "grassLight", frame: 1 },
      "2:18": { sourceId: "grassLight", frame: 1 },
      "2:19": { sourceId: "grassLight", frame: 1 },
      "2:20": { sourceId: "grassLight", frame: 1 },
      "2:21": { sourceId: "grassLight", frame: 1 },
      "2:22": { sourceId: "grassLight", frame: 1 },
      "2:23": { sourceId: "grassLight", frame: 1 },
      "2:24": { sourceId: "grassLight", frame: 1 },
      "2:25": { sourceId: "grassLight", frame: 1 },
      "2:26": { sourceId: "grassLight", frame: 1 },
      "2:27": { sourceId: "grassLight", frame: 1 },
      "2:28": { sourceId: "grassLight", frame: 1 },
      "2:29": { sourceId: "grassLight", frame: 1 },
      "2:30": { sourceId: "grassLight", frame: 1 },
      "2:31": { sourceId: "grassLight", frame: 1 },
      "2:32": { sourceId: "grassLight", frame: 1 },
      "2:33": { sourceId: "grassLight", frame: 1 },
      "2:34": { sourceId: "grassLight", frame: 2 },
      "2:7": { sourceId: "grassLight", frame: 11 },
      "20:35": { sourceId: "grassLight", frame: 13 },
      "20:5": { sourceId: "grassLight", frame: 11 },
      "21:35": { sourceId: "grassLight", frame: 13 },
      "21:5": { sourceId: "grassLight", frame: 11 },
      "22:35": { sourceId: "grassLight", frame: 13 },
      "22:5": { sourceId: "grassLight", frame: 22 },
      "22:6": { sourceId: "grassLight", frame: 23 },
      "22:7": { sourceId: "grassLight", frame: 17 },
      "23:10": { sourceId: "grassLight", frame: 23 },
      "23:11": { sourceId: "grassLight", frame: 23 },
      "23:12": { sourceId: "grassLight", frame: 23 },
      "23:13": { sourceId: "grassLight", frame: 23 },
      "23:14": { sourceId: "grassLight", frame: 23 },
      "23:15": { sourceId: "grassLight", frame: 23 },
      "23:16": { sourceId: "grassLight", frame: 23 },
      "23:17": { sourceId: "grassLight", frame: 17 },
      "23:34": { sourceId: "grassLight", frame: 16 },
      "23:35": { sourceId: "grassLight", frame: 24 },
      "23:7": { sourceId: "grassLight", frame: 22 },
      "23:8": { sourceId: "grassLight", frame: 23 },
      "23:9": { sourceId: "grassLight", frame: 23 },
      "24:17": { sourceId: "grassLight", frame: 22 },
      "24:18": { sourceId: "grassLight", frame: 23 },
      "24:19": { sourceId: "grassLight", frame: 23 },
      "24:20": { sourceId: "grassLight", frame: 23 },
      "24:21": { sourceId: "grassLight", frame: 23 },
      "24:22": { sourceId: "grassLight", frame: 23 },
      "24:23": { sourceId: "grassLight", frame: 23 },
      "24:24": { sourceId: "grassLight", frame: 23 },
      "24:25": { sourceId: "grassLight", frame: 23 },
      "24:26": { sourceId: "grassLight", frame: 23 },
      "24:27": { sourceId: "grassLight", frame: 23 },
      "24:28": { sourceId: "grassLight", frame: 23 },
      "24:29": { sourceId: "grassLight", frame: 23 },
      "24:30": { sourceId: "grassLight", frame: 23 },
      "24:31": { sourceId: "grassLight", frame: 23 },
      "24:32": { sourceId: "grassLight", frame: 23 },
      "24:33": { sourceId: "grassLight", frame: 23 },
      "24:34": { sourceId: "grassLight", frame: 24 },
      "3:34": { sourceId: "grassLight", frame: 27 },
      "3:35": { sourceId: "grassLight", frame: 2 },
      "3:7": { sourceId: "grassLight", frame: 11 },
      "4:35": { sourceId: "grassLight", frame: 13 },
      "4:6": { sourceId: "grassLight", frame: 0 },
      "4:7": { sourceId: "grassLight", frame: 28 },
      "5:35": { sourceId: "grassLight", frame: 13 },
      "5:5": { sourceId: "grassLight", frame: 0 },
      "5:6": { sourceId: "grassLight", frame: 28 },
      "6:35": { sourceId: "grassLight", frame: 13 },
      "6:5": { sourceId: "grassLight", frame: 11 },
      "7:35": { sourceId: "grassLight", frame: 13 },
      "7:5": { sourceId: "grassLight", frame: 11 },
      "8:35": { sourceId: "grassLight", frame: 13 },
      "8:5": { sourceId: "grassLight", frame: 11 },
      "9:35": { sourceId: "grassLight", frame: 13 },
      "9:5": { sourceId: "grassLight", frame: 11 },
    },
  },
  {
    id: "bush",
    label: "2 Bush",
    baseTile: { sourceId: "bush", frame: 0 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "......#..............................#..",
      "....................................#...",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      ".....................................#..",
      "......................................#.",
      ".....................................#..",
      "........................................",
      "....................................##..",
      "........................................",
      "......#.................................",
      "...#....................................",
      "........................................",
    ],
    overrides: {
      "17:37": { sourceId: "waterObjects", frame: 0 },
      "18:38": { sourceId: "waterObjects", frame: 1 },
      "19:37": { sourceId: "waterObjects", frame: 3 },
      "21:36": { sourceId: "waterObjects", frame: 4 },
      "21:37": { sourceId: "waterObjects", frame: 5 },
      "23:6": { sourceId: "waterObjects", frame: 9 },
      "24:3": { sourceId: "waterObjects", frame: 1 },
      "3:37": { sourceId: "waterObjects", frame: 0 },
      "3:6": { sourceId: "waterObjects", frame: 11 },
      "4:36": { sourceId: "waterObjects", frame: 3 },
    },
  },
  {
    id: "objects",
    label: "3 Objects",
    baseTile: { sourceId: "bush", frame: 0 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
    ],
    overrides: {},
  },
] as const;

export const PIXEL_FARM_GENERATED_OBJECTS = [
] as const;
