export const PIXEL_FARM_GENERATED_LAYERS = [
  {
    id: "soil",
    label: "0 Soil",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      ".......########.........................",
      ".......#########........................",
      "...#...############################.....",
      "...#...#############################....",
      "...#..##############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".......#############################....",
      ".................##################.....",
      "........................................",

    ],
    overrides: {
      "6:5": { sourceId: "soil", frame: 11 },
      "6:35": { sourceId: "soil", frame: 13 },
      "7:5": { sourceId: "soil", frame: 11 },
      "7:35": { sourceId: "soil", frame: 13 },
      "8:5": { sourceId: "soil", frame: 11 },
      "8:35": { sourceId: "soil", frame: 13 },
      "9:5": { sourceId: "soil", frame: 11 },
      "9:35": { sourceId: "soil", frame: 13 },
      "10:5": { sourceId: "soil", frame: 11 },
      "10:35": { sourceId: "soil", frame: 13 },
      "11:5": { sourceId: "soil", frame: 11 },
      "11:35": { sourceId: "soil", frame: 13 },
      "12:5": { sourceId: "soil", frame: 11 },
      "12:35": { sourceId: "soil", frame: 13 },
      "13:5": { sourceId: "soil", frame: 11 },
      "13:35": { sourceId: "soil", frame: 13 },
      "14:5": { sourceId: "soil", frame: 11 },
      "14:35": { sourceId: "soil", frame: 13 },
      "15:5": { sourceId: "soil", frame: 11 },
      "15:35": { sourceId: "soil", frame: 13 },
      "16:5": { sourceId: "soil", frame: 11 },
      "16:35": { sourceId: "soil", frame: 13 },
      "17:5": { sourceId: "soil", frame: 11 },
      "17:35": { sourceId: "soil", frame: 13 },
      "18:5": { sourceId: "soil", frame: 11 },
      "18:35": { sourceId: "soil", frame: 13 },
      "19:5": { sourceId: "soil", frame: 11 },
      "19:35": { sourceId: "soil", frame: 13 },
      "20:5": { sourceId: "soil", frame: 11 },
      "20:35": { sourceId: "soil", frame: 13 },
      "21:5": { sourceId: "soil", frame: 11 },
      "21:35": { sourceId: "soil", frame: 13 },
      "22:5": { sourceId: "soil", frame: 22 },
      "22:6": { sourceId: "soil", frame: 23 },
      "22:7": { sourceId: "soil", frame: 17 },
      "22:35": { sourceId: "soil", frame: 13 },
      "23:7": { sourceId: "soil", frame: 22 },
      "23:8": { sourceId: "soil", frame: 23 },
      "23:9": { sourceId: "soil", frame: 23 },
      "23:10": { sourceId: "soil", frame: 23 },
      "23:11": { sourceId: "soil", frame: 23 },
      "23:12": { sourceId: "soil", frame: 23 },
      "23:13": { sourceId: "soil", frame: 23 },
      "23:14": { sourceId: "soil", frame: 23 },
      "23:15": { sourceId: "soil", frame: 23 },
      "23:16": { sourceId: "soil", frame: 23 },
      "23:17": { sourceId: "soil", frame: 17 },
      "23:34": { sourceId: "soil", frame: 16 },
      "23:35": { sourceId: "soil", frame: 24 },
      "24:17": { sourceId: "soil", frame: 22 },
      "24:18": { sourceId: "soil", frame: 23 },
      "24:19": { sourceId: "soil", frame: 23 },
      "24:20": { sourceId: "soil", frame: 23 },
      "24:21": { sourceId: "soil", frame: 23 },
      "24:22": { sourceId: "soil", frame: 23 },
      "24:23": { sourceId: "soil", frame: 23 },
      "24:24": { sourceId: "soil", frame: 23 },
      "24:25": { sourceId: "soil", frame: 23 },
      "24:26": { sourceId: "soil", frame: 23 },
      "24:27": { sourceId: "soil", frame: 23 },
      "24:28": { sourceId: "soil", frame: 23 },
      "24:29": { sourceId: "soil", frame: 23 },
      "24:30": { sourceId: "soil", frame: 23 },
      "24:31": { sourceId: "soil", frame: 23 },
      "24:32": { sourceId: "soil", frame: 23 },
      "24:33": { sourceId: "soil", frame: 23 },
      "24:34": { sourceId: "soil", frame: 24 },
      "0:7": { sourceId: "soil", frame: 0 },
      "0:8": { sourceId: "soil", frame: 1 },
      "0:9": { sourceId: "soil", frame: 1 },
      "0:10": { sourceId: "soil", frame: 1 },
      "0:11": { sourceId: "soil", frame: 1 },
      "0:12": { sourceId: "soil", frame: 1 },
      "0:13": { sourceId: "soil", frame: 1 },
      "0:14": { sourceId: "soil", frame: 2 },
      "1:7": { sourceId: "soil", frame: 11 },
      "1:14": { sourceId: "soil", frame: 27 },
      "1:15": { sourceId: "soil", frame: 2 },
      "2:7": { sourceId: "soil", frame: 11 },
      "2:15": { sourceId: "soil", frame: 27 },
      "2:16": { sourceId: "soil", frame: 1 },
      "2:17": { sourceId: "soil", frame: 1 },
      "2:18": { sourceId: "soil", frame: 1 },
      "2:19": { sourceId: "soil", frame: 1 },
      "2:20": { sourceId: "soil", frame: 1 },
      "2:21": { sourceId: "soil", frame: 1 },
      "2:22": { sourceId: "soil", frame: 1 },
      "2:23": { sourceId: "soil", frame: 1 },
      "2:24": { sourceId: "soil", frame: 1 },
      "2:25": { sourceId: "soil", frame: 1 },
      "2:26": { sourceId: "soil", frame: 1 },
      "2:27": { sourceId: "soil", frame: 1 },
      "2:28": { sourceId: "soil", frame: 1 },
      "2:29": { sourceId: "soil", frame: 1 },
      "2:30": { sourceId: "soil", frame: 1 },
      "2:31": { sourceId: "soil", frame: 1 },
      "2:32": { sourceId: "soil", frame: 1 },
      "2:33": { sourceId: "soil", frame: 1 },
      "2:34": { sourceId: "soil", frame: 2 },
      "2:3": { sourceId: "soil", frame: 3 },
      "3:7": { sourceId: "soil", frame: 11 },
      "3:34": { sourceId: "soil", frame: 27 },
      "3:35": { sourceId: "soil", frame: 2 },
      "3:3": { sourceId: "soil", frame: 14 },
      "4:6": { sourceId: "soil", frame: 0 },
      "4:7": { sourceId: "soil", frame: 28 },
      "4:35": { sourceId: "soil", frame: 13 },
      "4:3": { sourceId: "soil", frame: 25 },
      "5:5": { sourceId: "soil", frame: 0 },
      "5:6": { sourceId: "soil", frame: 28 },
      "5:35": { sourceId: "soil", frame: 13 },
    },
  },
  {
    id: "grass-light",
    label: "1 Grass",
    baseTile: { sourceId: "grassLight", frame: 12 },
    mask: [
      ".......########.........................",
      ".......#########........................",
      ".......############################.....",
      ".......#############################....",
      "......##############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".##..###############################....",
      ".##..###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".....###############################....",
      ".......#############################....",
      ".................##################.....",
      "........................................",

    ],
    overrides: {
      "6:5": { sourceId: "grassLight", frame: 11 },
      "6:35": { sourceId: "grassLight", frame: 13 },
      "7:5": { sourceId: "grassLight", frame: 11 },
      "7:23": { sourceId: "grassLight", frame: 57 },
      "7:35": { sourceId: "grassLight", frame: 13 },
      "8:5": { sourceId: "grassLight", frame: 11 },
      "8:35": { sourceId: "grassLight", frame: 13 },
      "9:5": { sourceId: "grassLight", frame: 11 },
      "9:24": { sourceId: "grassLight", frame: 56 },
      "9:35": { sourceId: "grassLight", frame: 13 },
      "10:5": { sourceId: "grassLight", frame: 11 },
      "10:15": { sourceId: "grassLight", frame: 60 },
      "10:35": { sourceId: "grassLight", frame: 13 },
      "11:5": { sourceId: "grassLight", frame: 11 },
      "11:6": { sourceId: "grassHill", frame: 66 },
      "11:16": { sourceId: "grassLight", frame: 55 },
      "11:34": { sourceId: "grassHill", frame: 55 },
      "11:35": { sourceId: "grassLight", frame: 13 },
      "11:1": { sourceId: "grassLight", frame: 0 },
      "11:2": { sourceId: "grassLight", frame: 2 },
      "12:5": { sourceId: "grassLight", frame: 11 },
      "12:33": { sourceId: "grassLight", frame: 60 },
      "12:35": { sourceId: "grassLight", frame: 13 },
      "12:1": { sourceId: "grassLight", frame: 22 },
      "12:2": { sourceId: "grassLight", frame: 24 },
      "13:5": { sourceId: "grassLight", frame: 11 },
      "13:35": { sourceId: "grassLight", frame: 13 },
      "14:5": { sourceId: "grassLight", frame: 11 },
      "14:33": { sourceId: "grassHill", frame: 66 },
      "14:35": { sourceId: "grassLight", frame: 13 },
      "15:5": { sourceId: "grassLight", frame: 11 },
      "15:15": { sourceId: "grassHill", frame: 66 },
      "15:35": { sourceId: "grassLight", frame: 13 },
      "16:5": { sourceId: "grassLight", frame: 11 },
      "16:35": { sourceId: "grassLight", frame: 13 },
      "17:5": { sourceId: "grassLight", frame: 11 },
      "17:35": { sourceId: "grassLight", frame: 13 },
      "18:5": { sourceId: "grassLight", frame: 11 },
      "18:17": { sourceId: "grassLight", frame: 69 },
      "18:35": { sourceId: "grassLight", frame: 13 },
      "19:5": { sourceId: "grassLight", frame: 11 },
      "19:16": { sourceId: "grassLight", frame: 70 },
      "19:30": { sourceId: "grassLight", frame: 70 },
      "19:35": { sourceId: "grassLight", frame: 13 },
      "20:5": { sourceId: "grassLight", frame: 11 },
      "20:35": { sourceId: "grassLight", frame: 13 },
      "21:5": { sourceId: "grassLight", frame: 11 },
      "21:12": { sourceId: "grassLight", frame: 69 },
      "21:35": { sourceId: "grassLight", frame: 13 },
      "22:5": { sourceId: "grassLight", frame: 22 },
      "22:6": { sourceId: "grassLight", frame: 23 },
      "22:7": { sourceId: "grassLight", frame: 17 },
      "22:35": { sourceId: "grassLight", frame: 13 },
      "23:7": { sourceId: "grassLight", frame: 22 },
      "23:8": { sourceId: "grassLight", frame: 23 },
      "23:9": { sourceId: "grassLight", frame: 23 },
      "23:10": { sourceId: "grassLight", frame: 23 },
      "23:11": { sourceId: "grassLight", frame: 23 },
      "23:12": { sourceId: "grassLight", frame: 23 },
      "23:13": { sourceId: "grassLight", frame: 23 },
      "23:14": { sourceId: "grassLight", frame: 23 },
      "23:15": { sourceId: "grassLight", frame: 23 },
      "23:16": { sourceId: "grassLight", frame: 23 },
      "23:17": { sourceId: "grassLight", frame: 17 },
      "23:34": { sourceId: "grassLight", frame: 16 },
      "23:35": { sourceId: "grassLight", frame: 24 },
      "24:17": { sourceId: "grassLight", frame: 22 },
      "24:18": { sourceId: "grassLight", frame: 23 },
      "24:19": { sourceId: "grassLight", frame: 23 },
      "24:20": { sourceId: "grassLight", frame: 23 },
      "24:21": { sourceId: "grassLight", frame: 23 },
      "24:22": { sourceId: "grassLight", frame: 23 },
      "24:23": { sourceId: "grassLight", frame: 23 },
      "24:24": { sourceId: "grassLight", frame: 23 },
      "24:25": { sourceId: "grassLight", frame: 23 },
      "24:26": { sourceId: "grassLight", frame: 23 },
      "24:27": { sourceId: "grassLight", frame: 23 },
      "24:28": { sourceId: "grassLight", frame: 23 },
      "24:29": { sourceId: "grassLight", frame: 23 },
      "24:30": { sourceId: "grassLight", frame: 23 },
      "24:31": { sourceId: "grassLight", frame: 23 },
      "24:32": { sourceId: "grassLight", frame: 23 },
      "24:33": { sourceId: "grassLight", frame: 23 },
      "24:34": { sourceId: "grassLight", frame: 24 },
      "0:7": { sourceId: "grassLight", frame: 0 },
      "0:8": { sourceId: "grassLight", frame: 1 },
      "0:9": { sourceId: "grassLight", frame: 1 },
      "0:10": { sourceId: "grassLight", frame: 1 },
      "0:11": { sourceId: "grassLight", frame: 1 },
      "0:12": { sourceId: "grassLight", frame: 1 },
      "0:13": { sourceId: "grassLight", frame: 1 },
      "0:14": { sourceId: "grassLight", frame: 2 },
      "1:7": { sourceId: "grassLight", frame: 11 },
      "1:14": { sourceId: "grassLight", frame: 27 },
      "1:15": { sourceId: "grassLight", frame: 2 },
      "2:7": { sourceId: "grassLight", frame: 11 },
      "2:15": { sourceId: "grassLight", frame: 27 },
      "2:16": { sourceId: "grassLight", frame: 1 },
      "2:17": { sourceId: "grassLight", frame: 1 },
      "2:18": { sourceId: "grassLight", frame: 1 },
      "2:19": { sourceId: "grassLight", frame: 1 },
      "2:20": { sourceId: "grassLight", frame: 1 },
      "2:21": { sourceId: "grassLight", frame: 1 },
      "2:22": { sourceId: "grassLight", frame: 1 },
      "2:23": { sourceId: "grassLight", frame: 1 },
      "2:24": { sourceId: "grassLight", frame: 1 },
      "2:25": { sourceId: "grassLight", frame: 1 },
      "2:26": { sourceId: "grassLight", frame: 1 },
      "2:27": { sourceId: "grassLight", frame: 1 },
      "2:28": { sourceId: "grassLight", frame: 1 },
      "2:29": { sourceId: "grassLight", frame: 1 },
      "2:30": { sourceId: "grassLight", frame: 1 },
      "2:31": { sourceId: "grassLight", frame: 1 },
      "2:32": { sourceId: "grassLight", frame: 1 },
      "2:33": { sourceId: "grassLight", frame: 1 },
      "2:34": { sourceId: "grassLight", frame: 2 },
      "3:7": { sourceId: "grassLight", frame: 11 },
      "3:23": { sourceId: "grassLight", frame: 57 },
      "3:34": { sourceId: "grassLight", frame: 27 },
      "3:35": { sourceId: "grassLight", frame: 2 },
      "4:6": { sourceId: "grassLight", frame: 0 },
      "4:7": { sourceId: "grassLight", frame: 28 },
      "4:10": { sourceId: "grassLight", frame: 57 },
      "4:12": { sourceId: "grassHill", frame: 66 },
      "4:18": { sourceId: "grassLight", frame: 70 },
      "4:23": { sourceId: "grassLight", frame: 55 },
      "4:35": { sourceId: "grassLight", frame: 13 },
      "5:5": { sourceId: "grassLight", frame: 0 },
      "5:6": { sourceId: "grassLight", frame: 28 },
      "5:17": { sourceId: "grassLight", frame: 57 },
      "5:35": { sourceId: "grassLight", frame: 13 },
    },
  },
  {
    id: "bush",
    label: "2 Bush",
    baseTile: { sourceId: "bush", frame: 0 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "......#..............................#..",
      "....................................#...",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      ".....................................#..",
      "......................................#.",
      ".....................................#..",
      "........................................",
      "....................................##..",
      "........................................",
      "......#.................................",
      "...#....................................",
      "........................................",

    ],
    overrides: {
      "17:37": { sourceId: "waterObjects", frame: 0 },
      "18:38": { sourceId: "waterObjects", frame: 1 },
      "19:37": { sourceId: "waterObjects", frame: 3 },
      "21:36": { sourceId: "waterObjects", frame: 4 },
      "21:37": { sourceId: "waterObjects", frame: 5 },
      "23:6": { sourceId: "waterObjects", frame: 9 },
      "24:3": { sourceId: "waterObjects", frame: 1 },
      "3:6": { sourceId: "waterObjects", frame: 11 },
      "3:37": { sourceId: "waterObjects", frame: 0 },
      "4:36": { sourceId: "waterObjects", frame: 3 },
    },
  },
  {
    id: "layer-5",
    label: "2-1 grassHill",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      "........................................",
      "........................................",
      ".........###............................",
      ".........###......####..##########......",
      "........####......####..##...######.....",
      "........###.......####..##...######.....",
      "........###.......####..###########.....",
      "........................###########.....",
      "........................###########.....",
      "..........................#########.....",
      ".........###..............#########.....",
      "......######...................##.......",
      "......######...................##.......",
      "......##.###............................",
      "......######............................",
      "......######............................",
      "........................................",
      "........................................",
      "........##..............................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",

    ],
    overrides: {
      "6:8": { sourceId: "grassDark", frame: 22 },
      "6:9": { sourceId: "grassDark", frame: 23 },
      "6:10": { sourceId: "grassDark", frame: 24 },
      "6:18": { sourceId: "grassHill", frame: 22 },
      "6:19": { sourceId: "grassHill", frame: 23 },
      "6:20": { sourceId: "grassHill", frame: 23 },
      "6:21": { sourceId: "grassHill", frame: 24 },
      "6:24": { sourceId: "grassHill", frame: 11 },
      "6:25": { sourceId: "grassLight", frame: 66 },
      "6:26": { sourceId: "grassHill", frame: 12 },
      "6:27": { sourceId: "grassHill", frame: 12 },
      "6:28": { sourceId: "grassHill", frame: 12 },
      "6:29": { sourceId: "grassHill", frame: 12 },
      "6:30": { sourceId: "grassHill", frame: 12 },
      "6:31": { sourceId: "grassHill", frame: 12 },
      "6:32": { sourceId: "grassHill", frame: 12 },
      "6:33": { sourceId: "grassHill", frame: 12 },
      "6:34": { sourceId: "grassHill", frame: 13 },
      "7:24": { sourceId: "grassHill", frame: 11 },
      "7:25": { sourceId: "grassHill", frame: 57 },
      "7:26": { sourceId: "grassLight", frame: 71 },
      "7:27": { sourceId: "grassHill", frame: 12 },
      "7:28": { sourceId: "grassHill", frame: 12 },
      "7:29": { sourceId: "grassHill", frame: 12 },
      "7:30": { sourceId: "grassHill", frame: 12 },
      "7:31": { sourceId: "grassHill", frame: 12 },
      "7:32": { sourceId: "grassHill", frame: 12 },
      "7:33": { sourceId: "grassHill", frame: 12 },
      "7:34": { sourceId: "grassHill", frame: 13 },
      "8:24": { sourceId: "grassHill", frame: 22 },
      "8:25": { sourceId: "grassHill", frame: 23 },
      "8:26": { sourceId: "grassHill", frame: 17 },
      "8:27": { sourceId: "grassHill", frame: 12 },
      "8:28": { sourceId: "grassHill", frame: 12 },
      "8:29": { sourceId: "grassHill", frame: 12 },
      "8:30": { sourceId: "grassHill", frame: 12 },
      "8:31": { sourceId: "grassHill", frame: 12 },
      "8:32": { sourceId: "grassHill", frame: 12 },
      "8:33": { sourceId: "grassLight", frame: 66 },
      "8:34": { sourceId: "grassHill", frame: 13 },
      "9:26": { sourceId: "grassHill", frame: 11 },
      "9:27": { sourceId: "grassHill", frame: 12 },
      "9:28": { sourceId: "grassHill", frame: 12 },
      "9:29": { sourceId: "grassHill", frame: 12 },
      "9:30": { sourceId: "grassHill", frame: 12 },
      "9:31": { sourceId: "grassHill", frame: 12 },
      "9:32": { sourceId: "grassHill", frame: 70 },
      "9:33": { sourceId: "grassHill", frame: 12 },
      "9:34": { sourceId: "grassHill", frame: 13 },
      "10:9": { sourceId: "grassDark", frame: 0 },
      "10:10": { sourceId: "grassDark", frame: 1 },
      "10:11": { sourceId: "grassDark", frame: 2 },
      "10:26": { sourceId: "grassHill", frame: 22 },
      "10:27": { sourceId: "grassHill", frame: 23 },
      "10:28": { sourceId: "grassHill", frame: 23 },
      "10:29": { sourceId: "grassHill", frame: 23 },
      "10:30": { sourceId: "grassHill", frame: 23 },
      "10:31": { sourceId: "grassHillSlopes", frame: 4 },
      "10:32": { sourceId: "grassHillSlopes", frame: 5 },
      "10:33": { sourceId: "grassHill", frame: 23 },
      "10:34": { sourceId: "grassHill", frame: 24 },
      "11:6": { sourceId: "grassDark", frame: 0 },
      "11:7": { sourceId: "grassDark", frame: 1 },
      "11:8": { sourceId: "grassDark", frame: 1 },
      "11:9": { sourceId: "grassDark", frame: 28 },
      "11:10": { sourceId: "grassDark", frame: 12 },
      "11:11": { sourceId: "grassDark", frame: 13 },
      "11:31": { sourceId: "grassHillSlopes", frame: 10 },
      "11:32": { sourceId: "grassHillSlopes", frame: 11 },
      "12:6": { sourceId: "grassDark", frame: 11 },
      "12:7": { sourceId: "grassDark", frame: 16 },
      "12:8": { sourceId: "grassDark", frame: 23 },
      "12:9": { sourceId: "grassDark", frame: 17 },
      "12:10": { sourceId: "grassDark", frame: 12 },
      "12:11": { sourceId: "grassDark", frame: 13 },
      "12:31": { sourceId: "grassHillSlopes", frame: 16 },
      "12:32": { sourceId: "grassHillSlopes", frame: 17 },
      "13:6": { sourceId: "grassDark", frame: 11 },
      "13:7": { sourceId: "grassDark", frame: 13 },
      "13:9": { sourceId: "grassDark", frame: 11 },
      "13:10": { sourceId: "grassDark", frame: 12 },
      "13:11": { sourceId: "grassDark", frame: 13 },
      "14:6": { sourceId: "grassDark", frame: 11 },
      "14:7": { sourceId: "grassDark", frame: 27 },
      "14:8": { sourceId: "grassDark", frame: 1 },
      "14:9": { sourceId: "grassDark", frame: 28 },
      "14:10": { sourceId: "grassDark", frame: 12 },
      "14:11": { sourceId: "grassDark", frame: 13 },
      "15:6": { sourceId: "grassDark", frame: 22 },
      "15:7": { sourceId: "grassDark", frame: 23 },
      "15:8": { sourceId: "grassDark", frame: 23 },
      "15:9": { sourceId: "grassDark", frame: 23 },
      "15:10": { sourceId: "grassDark", frame: 23 },
      "15:11": { sourceId: "grassDark", frame: 24 },
      "18:8": { sourceId: "grassDark", frame: 33 },
      "18:9": { sourceId: "grassDark", frame: 35 },
      "2:9": { sourceId: "grassDark", frame: 0 },
      "2:10": { sourceId: "grassDark", frame: 1 },
      "2:11": { sourceId: "grassDark", frame: 2 },
      "3:9": { sourceId: "grassDark", frame: 11 },
      "3:10": { sourceId: "grassDark", frame: 12 },
      "3:11": { sourceId: "grassDark", frame: 13 },
      "3:18": { sourceId: "grassHill", frame: 0 },
      "3:19": { sourceId: "grassHill", frame: 1 },
      "3:20": { sourceId: "grassHill", frame: 1 },
      "3:21": { sourceId: "grassHill", frame: 2 },
      "3:24": { sourceId: "grassHill", frame: 0 },
      "3:25": { sourceId: "grassHill", frame: 1 },
      "3:26": { sourceId: "grassHill", frame: 1 },
      "3:27": { sourceId: "grassHill", frame: 1 },
      "3:28": { sourceId: "grassHill", frame: 1 },
      "3:29": { sourceId: "grassHill", frame: 1 },
      "3:30": { sourceId: "grassHill", frame: 1 },
      "3:31": { sourceId: "grassHill", frame: 1 },
      "3:32": { sourceId: "grassHill", frame: 1 },
      "3:33": { sourceId: "grassHill", frame: 2 },
      "4:8": { sourceId: "grassDark", frame: 0 },
      "4:9": { sourceId: "grassDark", frame: 28 },
      "4:10": { sourceId: "grassDark", frame: 16 },
      "4:11": { sourceId: "grassDark", frame: 24 },
      "4:18": { sourceId: "grassHill", frame: 11 },
      "4:19": { sourceId: "grassHill", frame: 12 },
      "4:20": { sourceId: "grassHill", frame: 66 },
      "4:21": { sourceId: "grassHill", frame: 13 },
      "4:24": { sourceId: "grassHill", frame: 11 },
      "4:25": { sourceId: "grassHill", frame: 55 },
      "4:29": { sourceId: "grassHill", frame: 12 },
      "4:30": { sourceId: "grassHill", frame: 12 },
      "4:31": { sourceId: "grassHill", frame: 12 },
      "4:32": { sourceId: "grassHill", frame: 12 },
      "4:33": { sourceId: "grassHill", frame: 27 },
      "4:34": { sourceId: "grassHill", frame: 2 },
      "5:8": { sourceId: "grassDark", frame: 11 },
      "5:9": { sourceId: "grassDark", frame: 12 },
      "5:10": { sourceId: "grassDark", frame: 13 },
      "5:18": { sourceId: "grassHill", frame: 11 },
      "5:19": { sourceId: "grassHill", frame: 66 },
      "5:20": { sourceId: "grassHill", frame: 12 },
      "5:21": { sourceId: "grassHill", frame: 13 },
      "5:24": { sourceId: "grassHill", frame: 11 },
      "5:25": { sourceId: "grassHill", frame: 12 },
      "5:29": { sourceId: "grassHill", frame: 12 },
      "5:30": { sourceId: "grassHill", frame: 12 },
      "5:31": { sourceId: "grassHill", frame: 12 },
      "5:32": { sourceId: "grassHill", frame: 60 },
      "5:33": { sourceId: "grassHill", frame: 12 },
      "5:34": { sourceId: "grassHill", frame: 13 },
    },
  },
  {
    id: "layer-6",
    label: "2-2 tiled",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      "........................................",
      "........###.............................",
      "........#...............................",
      "........#...............................",
      ".......##.................###...........",
      ".......##............####...............",
      "........................................",
      "........................................",
      "........................................",
      ".................###....................",
      "........................................",
      ".................######.................",
      "...............########.................",
      "...............#############............",
      "...............#############...###......",
      "...............#############..####......",
      "................###########...####......",
      "..............................###.......",
      "........................................",
      "....................########............",
      "...................#########..####......",
      "..................##########..####......",
      "..................##########..####......",
      "........................................",
      "........................................",
      "........................................",

    ],
    overrides: {
      "9:17": { sourceId: "stonePath", frame: 13 },
      "9:18": { sourceId: "stonePath", frame: 14 },
      "9:19": { sourceId: "stonePath", frame: 15 },
      "11:17": { sourceId: "tilledDirtWide", frame: 0 },
      "11:18": { sourceId: "tilledDirtWide", frame: 60 },
      "11:19": { sourceId: "tilledDirtWide", frame: 62 },
      "11:20": { sourceId: "tilledDirtWide", frame: 62 },
      "11:21": { sourceId: "tilledDirtWide", frame: 1 },
      "11:22": { sourceId: "tilledDirtWide", frame: 2 },
      "12:15": { sourceId: "tilledDirtWide", frame: 0 },
      "12:16": { sourceId: "tilledDirtWide", frame: 1 },
      "12:17": { sourceId: "tilledDirtWide", frame: 28 },
      "12:18": { sourceId: "tilledDirtWide", frame: 12 },
      "12:19": { sourceId: "tilledDirtWide", frame: 66 },
      "12:20": { sourceId: "tilledDirtWide", frame: 12 },
      "12:21": { sourceId: "tilledDirtWide", frame: 67 },
      "12:22": { sourceId: "tilledDirtWide", frame: 13 },
      "13:15": { sourceId: "tilledDirtWide", frame: 74 },
      "13:16": { sourceId: "tilledDirtWide", frame: 66 },
      "13:17": { sourceId: "tilledDirtWide", frame: 12 },
      "13:18": { sourceId: "tilledDirtWide", frame: 12 },
      "13:19": { sourceId: "tilledDirtWide", frame: 12 },
      "13:20": { sourceId: "tilledDirtWide", frame: 67 },
      "13:21": { sourceId: "tilledDirtWide", frame: 66 },
      "13:22": { sourceId: "tilledDirtWide", frame: 27 },
      "13:23": { sourceId: "tilledDirtWide", frame: 1 },
      "13:24": { sourceId: "tilledDirtWide", frame: 62 },
      "13:25": { sourceId: "tilledDirtWide", frame: 62 },
      "13:26": { sourceId: "tilledDirtWide", frame: 1 },
      "13:27": { sourceId: "tilledDirtWide", frame: 2 },
      "14:15": { sourceId: "tilledDirtWide", frame: 74 },
      "14:16": { sourceId: "tilledDirtWide", frame: 66 },
      "14:17": { sourceId: "tilledDirtWide", frame: 66 },
      "14:18": { sourceId: "tilledDirtWide", frame: 12 },
      "14:19": { sourceId: "tilledDirtWide", frame: 12 },
      "14:20": { sourceId: "tilledDirtWide", frame: 12 },
      "14:21": { sourceId: "tilledDirtWide", frame: 12 },
      "14:22": { sourceId: "tilledDirtWide", frame: 12 },
      "14:23": { sourceId: "tilledDirtWide", frame: 12 },
      "14:24": { sourceId: "tilledDirtWide", frame: 12 },
      "14:25": { sourceId: "tilledDirtWide", frame: 12 },
      "14:26": { sourceId: "tilledDirtWide", frame: 66 },
      "14:27": { sourceId: "tilledDirtWide", frame: 75 },
      "14:31": { sourceId: "tilledDirtWide", frame: 0 },
      "14:32": { sourceId: "tilledDirtWide", frame: 60 },
      "14:33": { sourceId: "tilledDirtWide", frame: 2 },
      "15:15": { sourceId: "tilledDirtWide", frame: 22 },
      "15:16": { sourceId: "tilledDirtWide", frame: 17 },
      "15:17": { sourceId: "tilledDirtWide", frame: 12 },
      "15:18": { sourceId: "tilledDirtWide", frame: 67 },
      "15:19": { sourceId: "tilledDirtWide", frame: 12 },
      "15:20": { sourceId: "tilledDirtWide", frame: 66 },
      "15:21": { sourceId: "tilledDirtWide", frame: 12 },
      "15:22": { sourceId: "tilledDirtWide", frame: 12 },
      "15:23": { sourceId: "tilledDirtWide", frame: 66 },
      "15:24": { sourceId: "tilledDirtWide", frame: 66 },
      "15:25": { sourceId: "tilledDirtWide", frame: 12 },
      "15:26": { sourceId: "tilledDirtWide", frame: 16 },
      "15:27": { sourceId: "tilledDirtWide", frame: 24 },
      "15:30": { sourceId: "tilledDirtWide", frame: 0 },
      "15:31": { sourceId: "tilledDirtWide", frame: 28 },
      "15:32": { sourceId: "tilledDirtWide", frame: 57 },
      "15:33": { sourceId: "tilledDirtWide", frame: 13 },
      "16:16": { sourceId: "tilledDirtWide", frame: 22 },
      "16:17": { sourceId: "tilledDirtWide", frame: 71 },
      "16:18": { sourceId: "tilledDirtWide", frame: 23 },
      "16:19": { sourceId: "tilledDirtWide", frame: 23 },
      "16:20": { sourceId: "tilledDirtWide", frame: 71 },
      "16:21": { sourceId: "tilledDirtWide", frame: 72 },
      "16:22": { sourceId: "tilledDirtWide", frame: 72 },
      "16:23": { sourceId: "tilledDirtWide", frame: 23 },
      "16:24": { sourceId: "tilledDirtWide", frame: 23 },
      "16:25": { sourceId: "tilledDirtWide", frame: 23 },
      "16:26": { sourceId: "tilledDirtWide", frame: 24 },
      "16:30": { sourceId: "tilledDirtWide", frame: 74 },
      "16:31": { sourceId: "tilledDirtWide", frame: 66 },
      "16:32": { sourceId: "tilledDirtWide", frame: 16 },
      "16:33": { sourceId: "tilledDirtWide", frame: 24 },
      "17:30": { sourceId: "tilledDirtWide", frame: 22 },
      "17:31": { sourceId: "tilledDirtWide", frame: 72 },
      "17:32": { sourceId: "tilledDirtWide", frame: 24 },
      "19:20": { sourceId: "tilledDirtWide", frame: 0 },
      "19:21": { sourceId: "tilledDirtWide", frame: 60 },
      "19:22": { sourceId: "tilledDirtWide", frame: 61 },
      "19:23": { sourceId: "tilledDirtWide", frame: 62 },
      "19:24": { sourceId: "tilledDirtWide", frame: 1 },
      "19:25": { sourceId: "tilledDirtWide", frame: 1 },
      "19:26": { sourceId: "tilledDirtWide", frame: 62 },
      "19:27": { sourceId: "tilledDirtWide", frame: 2 },
      "20:19": { sourceId: "tilledDirtWide", frame: 0 },
      "20:20": { sourceId: "tilledDirtWide", frame: 28 },
      "20:21": { sourceId: "tilledDirtWide", frame: 66 },
      "20:22": { sourceId: "tilledDirtWide", frame: 12 },
      "20:23": { sourceId: "tilledDirtWide", frame: 12 },
      "20:24": { sourceId: "tilledDirtWide", frame: 12 },
      "20:25": { sourceId: "tilledDirtWide", frame: 66 },
      "20:26": { sourceId: "tilledDirtWide", frame: 67 },
      "20:27": { sourceId: "tilledDirtWide", frame: 64 },
      "20:30": { sourceId: "tilledDirtWide", frame: 0 },
      "20:31": { sourceId: "tilledDirtWide", frame: 1 },
      "20:32": { sourceId: "tilledDirtWide", frame: 62 },
      "20:33": { sourceId: "tilledDirtWide", frame: 2 },
      "21:18": { sourceId: "tilledDirtWide", frame: 0 },
      "21:19": { sourceId: "tilledDirtWide", frame: 28 },
      "21:20": { sourceId: "tilledDirtWide", frame: 66 },
      "21:21": { sourceId: "tilledDirtWide", frame: 12 },
      "21:22": { sourceId: "tilledDirtWide", frame: 67 },
      "21:23": { sourceId: "tilledDirtWide", frame: 12 },
      "21:24": { sourceId: "tilledDirtWide", frame: 66 },
      "21:25": { sourceId: "tilledDirtWide", frame: 12 },
      "21:26": { sourceId: "tilledDirtWide", frame: 66 },
      "21:27": { sourceId: "tilledDirtWide", frame: 75 },
      "21:30": { sourceId: "tilledDirtWide", frame: 74 },
      "21:31": { sourceId: "tilledDirtWide", frame: 66 },
      "21:32": { sourceId: "tilledDirtWide", frame: 66 },
      "21:33": { sourceId: "tilledDirtWide", frame: 64 },
      "22:18": { sourceId: "tilledDirtWide", frame: 22 },
      "22:19": { sourceId: "tilledDirtWide", frame: 23 },
      "22:20": { sourceId: "tilledDirtWide", frame: 23 },
      "22:21": { sourceId: "tilledDirtWide", frame: 72 },
      "22:22": { sourceId: "tilledDirtWide", frame: 72 },
      "22:23": { sourceId: "tilledDirtWide", frame: 71 },
      "22:24": { sourceId: "tilledDirtWide", frame: 23 },
      "22:25": { sourceId: "tilledDirtWide", frame: 23 },
      "22:26": { sourceId: "tilledDirtWide", frame: 23 },
      "22:27": { sourceId: "tilledDirtWide", frame: 24 },
      "22:30": { sourceId: "tilledDirtWide", frame: 22 },
      "22:31": { sourceId: "tilledDirtWide", frame: 72 },
      "22:32": { sourceId: "tilledDirtWide", frame: 23 },
      "22:33": { sourceId: "tilledDirtWide", frame: 24 },
      "1:8": { sourceId: "bush", frame: 0 },
      "1:9": { sourceId: "bush", frame: 34 },
      "1:10": { sourceId: "bush", frame: 35 },
      "2:8": { sourceId: "bush", frame: 14 },
      "3:8": { sourceId: "bush", frame: 14 },
      "4:7": { sourceId: "bush", frame: 4 },
      "4:8": { sourceId: "bush", frame: 13 },
      "4:26": { sourceId: "grassDark", frame: 33 },
      "4:27": { sourceId: "grassDark", frame: 34 },
      "4:28": { sourceId: "grassDark", frame: 35 },
      "5:7": { sourceId: "bush", frame: 22 },
      "5:8": { sourceId: "bush", frame: 24 },
      "5:21": { sourceId: "woodenBridge", frame: 0 },
      "5:22": { sourceId: "woodenBridge", frame: 8 },
      "5:23": { sourceId: "woodenBridge", frame: 8 },
      "5:24": { sourceId: "woodenBridge", frame: 1 },
    },
  },
  {
    id: "layer-7",
    label: "2-3 house",
    baseTile: { sourceId: "soil", frame: 12 },
    mask: [
      "........................................",
      "........................................",
      "..............................###.......",
      "..............................###.......",
      "..............................###.......",
      "........................................",
      ".............###........................",
      ".............####.......................",
      ".............####.......................",
      ".............####.......................",
      ".............####.......................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",

    ],
    overrides: {
      "6:13": { sourceId: "chickenHouses", frame: 4 },
      "6:14": { sourceId: "chickenHouses", frame: 5 },
      "6:15": { sourceId: "chickenHouses", frame: 6 },
      "7:13": { sourceId: "chickenHouses", frame: 28 },
      "7:14": { sourceId: "chickenHouses", frame: 29 },
      "7:15": { sourceId: "chickenHouses", frame: 30 },
      "7:16": { sourceId: "chickenHouses", frame: 31 },
      "8:13": { sourceId: "chickenHouses", frame: 52 },
      "8:14": { sourceId: "chickenHouses", frame: 53 },
      "8:15": { sourceId: "chickenHouses", frame: 54 },
      "8:16": { sourceId: "chickenHouses", frame: 55 },
      "9:13": { sourceId: "chickenHouses", frame: 76 },
      "9:14": { sourceId: "chickenHouses", frame: 77 },
      "9:15": { sourceId: "chickenHouses", frame: 78 },
      "9:16": { sourceId: "chickenHouses", frame: 79 },
      "10:13": { sourceId: "chickenHouses", frame: 100 },
      "10:14": { sourceId: "chickenHouses", frame: 101 },
      "10:15": { sourceId: "chickenHouses", frame: 102 },
      "10:16": { sourceId: "chickenHouses", frame: 103 },
      "2:30": { sourceId: "chickenHouses", frame: 198 },
      "2:31": { sourceId: "chickenHouses", frame: 199 },
      "2:32": { sourceId: "chickenHouses", frame: 200 },
      "3:30": { sourceId: "chickenHouses", frame: 222 },
      "3:31": { sourceId: "chickenHouses", frame: 223 },
      "3:32": { sourceId: "chickenHouses", frame: 224 },
      "4:30": { sourceId: "chickenHouses", frame: 246 },
      "4:31": { sourceId: "chickenHouses", frame: 247 },
      "4:32": { sourceId: "chickenHouses", frame: 248 },
    },
  },
  {
    id: "layer-8",
    label: "2-4 tree base",
    baseTile: { sourceId: "treesStumpsBushes", frame: 22 },
    mask: [
      "........................................",
      "........................................",
      "...................##...................",
      "...................##...................",
      "........................................",
      "...........#............................",
      "..........#.............................",
      "........................................",
      "........................................",
      "..........##.................#..........",
      "......##..##............................",
      "......###.........................#.....",
      "........................................",
      ".........###............................",
      ".........###............................",
      ".........###............................",
      "........................................",
      "........................................",
      ".....#..................................",
      ".....##.................................",
      ".....##.................................",
      ".....##.................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",

    ],
    overrides: {
      "6:10": { sourceId: "treesStumpsBushes", frame: 38 },
      "9:10": { sourceId: "treesStumpsBushes", frame: 5 },
      "9:11": { sourceId: "treesStumpsBushes", frame: 6 },
      "9:29": { sourceId: "mushroomsFlowersStones", frame: 26 },
      "10:6": { sourceId: "treesStumpsBushes", frame: 5 },
      "10:7": { sourceId: "treesStumpsBushes", frame: 6 },
      "10:10": { sourceId: "treesStumpsBushes", frame: 17 },
      "10:11": { sourceId: "treesStumpsBushes", frame: 18 },
      "11:6": { sourceId: "treesStumpsBushes", frame: 17 },
      "11:7": { sourceId: "treesStumpsBushes", frame: 18 },
      "11:8": { sourceId: "treesStumpsBushes", frame: 38 },
      "11:34": { sourceId: "mushroomsFlowersStones", frame: 27 },
      "13:9": { sourceId: "treesStumpsBushes", frame: 45 },
      "13:10": { sourceId: "treesStumpsBushes", frame: 46 },
      "13:11": { sourceId: "treesStumpsBushes", frame: 47 },
      "14:9": { sourceId: "treesStumpsBushes", frame: 57 },
      "14:10": { sourceId: "treesStumpsBushes", frame: 58 },
      "14:11": { sourceId: "treesStumpsBushes", frame: 59 },
      "15:9": { sourceId: "treesStumpsBushes", frame: 69 },
      "15:10": { sourceId: "treesStumpsBushes", frame: 70 },
      "15:11": { sourceId: "treesStumpsBushes", frame: 71 },
      "18:5": { sourceId: "treesStumpsBushes", frame: 0 },
      "19:5": { sourceId: "treesStumpsBushes", frame: 12 },
      "19:6": { sourceId: "treesStumpsBushes", frame: 36 },
      "20:5": { sourceId: "treesStumpsBushes", frame: 7 },
      "20:6": { sourceId: "treesStumpsBushes", frame: 8 },
      "21:5": { sourceId: "treesStumpsBushes", frame: 19 },
      "21:6": { sourceId: "treesStumpsBushes", frame: 20 },
      "2:19": { sourceId: "treesStumpsBushes", frame: 9 },
      "2:20": { sourceId: "treesStumpsBushes", frame: 10 },
      "3:19": { sourceId: "treesStumpsBushes", frame: 21 },
      "5:11": { sourceId: "treesStumpsBushes", frame: 40 },
    },
  },
  {
    id: "objects",
    label: "3 Objects",
    baseTile: { sourceId: "bush", frame: 0 },
    mask: [
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",
      "........................................",

    ],
    overrides: {},
  },
] as const;

export const PIXEL_FARM_GENERATED_OBJECTS = [
  {
    id: "object-1",
    layerId: "objects",
    sourceId: "signs",
    frame: 15,
    row: 14,
    column: 30,
  },
  {
    id: "object-2",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 17,
    column: 33,
  },
  {
    id: "object-3",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 24,
    row: 17,
    column: 32,
  },
  {
    id: "object-4",
    layerId: "objects",
    sourceId: "fences",
    frame: 0,
    row: 15,
    column: 34,
  },
  {
    id: "object-5",
    layerId: "objects",
    sourceId: "fences",
    frame: 16,
    row: 16,
    column: 34,
  },
  {
    id: "object-6",
    layerId: "objects",
    sourceId: "fences",
    frame: 0,
    row: 21,
    column: 34,
  },
  {
    id: "object-7",
    layerId: "objects",
    sourceId: "fences",
    frame: 16,
    row: 22,
    column: 34,
  },
  {
    id: "object-8",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 23,
    column: 31,
  },
  {
    id: "object-9",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 23,
    column: 33,
  },
  {
    id: "object-10",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 23,
    column: 32,
  },
  {
    id: "object-11",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 23,
    column: 19,
  },
  {
    id: "object-12",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 23,
    column: 20,
  },
  {
    id: "object-13",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 23,
    column: 21,
  },
  {
    id: "object-14",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 23,
    column: 24,
  },
  {
    id: "object-15",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 23,
    column: 25,
  },
  {
    id: "object-16",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 23,
    column: 26,
  },
  {
    id: "object-17",
    layerId: "objects",
    sourceId: "fences",
    frame: 25,
    row: 3,
    column: 26,
  },
  {
    id: "object-18",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 3,
    column: 27,
  },
  {
    id: "object-19",
    layerId: "objects",
    sourceId: "fences",
    frame: 27,
    row: 3,
    column: 28,
  },
  {
    id: "object-23",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 40,
    row: 4,
    column: 30,
  },
  {
    id: "object-24",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 41,
    row: 4,
    column: 33,
  },
  {
    id: "object-22",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 12,
    row: 3,
    column: 25,
  },
  {
    id: "object-26",
    layerId: "objects",
    sourceId: "fences",
    frame: 17,
    row: 21,
    column: 7,
  },
  {
    id: "object-27",
    layerId: "objects",
    sourceId: "fences",
    frame: 3,
    row: 21,
    column: 8,
  },
  {
    id: "object-28",
    layerId: "objects",
    sourceId: "fences",
    frame: 17,
    row: 22,
    column: 8,
  },
  {
    id: "object-29",
    layerId: "objects",
    sourceId: "fences",
    frame: 20,
    row: 22,
    column: 9,
  },
  {
    id: "object-30",
    layerId: "objects",
    sourceId: "fences",
    frame: 23,
    row: 22,
    column: 10,
  },
  {
    id: "object-31",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 22,
    column: 11,
  },
  {
    id: "object-32",
    layerId: "objects",
    sourceId: "fences",
    frame: 26,
    row: 22,
    column: 12,
  },
  {
    id: "object-33",
    layerId: "objects",
    sourceId: "fences",
    frame: 19,
    row: 22,
    column: 13,
  },
  {
    id: "object-34",
    layerId: "objects",
    sourceId: "fences",
    frame: 0,
    row: 21,
    column: 13,
  },
  {
    id: "object-35",
    layerId: "objects",
    sourceId: "fences",
    frame: 8,
    row: 20,
    column: 7,
  },
  {
    id: "object-36",
    layerId: "objects",
    sourceId: "fences",
    frame: 8,
    row: 19,
    column: 7,
  },
  {
    id: "object-37",
    layerId: "objects",
    sourceId: "fences",
    frame: 8,
    row: 18,
    column: 7,
  },
  {
    id: "object-38",
    layerId: "objects",
    sourceId: "fences",
    frame: 1,
    row: 17,
    column: 7,
  },
  {
    id: "object-39",
    layerId: "objects",
    sourceId: "fences",
    frame: 4,
    row: 17,
    column: 8,
  },
  {
    id: "object-40",
    layerId: "objects",
    sourceId: "fences",
    frame: 7,
    row: 17,
    column: 9,
  },
  {
    id: "object-41",
    layerId: "objects",
    sourceId: "fences",
    frame: 2,
    row: 17,
    column: 10,
  },
  {
    id: "object-42",
    layerId: "objects",
    sourceId: "fences",
    frame: 20,
    row: 17,
    column: 11,
  },
  {
    id: "object-43",
    layerId: "objects",
    sourceId: "fences",
    frame: 23,
    row: 17,
    column: 12,
  },
  {
    id: "object-44",
    layerId: "objects",
    sourceId: "fences",
    frame: 3,
    row: 17,
    column: 13,
  },
  {
    id: "object-45",
    layerId: "objects",
    sourceId: "fences",
    frame: 16,
    row: 18,
    column: 13,
  },
  {
    id: "object-46",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 9,
    row: 20,
    column: 8,
  },
  {
    id: "object-47",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 9,
    row: 18,
    column: 12,
  },
  {
    id: "object-48",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 10,
    row: 21,
    column: 9,
  },
  {
    id: "object-49",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 3,
    row: 21,
    column: 14,
  },
  {
    id: "object-50",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 6,
    row: 22,
    column: 15,
  },
  {
    id: "object-51",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 7,
    row: 22,
    column: 16,
  },
  {
    id: "object-74",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 22,
    column: 7,
  },
  {
    id: "object-75",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 40,
    row: 23,
    column: 30,
  },
  {
    id: "object-76",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 41,
    row: 22,
    column: 29,
  },
  {
    id: "object-77",
    layerId: "objects",
    sourceId: "workStation",
    frame: 0,
    row: 8,
    column: 27,
  },
  {
    id: "object-78",
    layerId: "objects",
    sourceId: "workStation",
    frame: 1,
    row: 8,
    column: 28,
  },
  {
    id: "object-79",
    layerId: "objects",
    sourceId: "workStation",
    frame: 2,
    row: 9,
    column: 27,
  },
  {
    id: "object-80",
    layerId: "objects",
    sourceId: "workStation",
    frame: 3,
    row: 9,
    column: 28,
  },
  {
    id: "object-86",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 0,
    row: 2,
    column: 25,
  },
  {
    id: "object-87",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 13,
    row: 1,
    column: 13,
  },
  {
    id: "object-88",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 14,
    row: 1,
    column: 14,
  },
  {
    id: "object-89",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 1,
    row: 0,
    column: 13,
  },
  {
    id: "object-90",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 2,
    row: 0,
    column: 14,
  },
  {
    id: "object-103",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 13,
    row: 7,
    column: 6,
  },
  {
    id: "object-108",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 1,
    row: 6,
    column: 6,
  },
  {
    id: "object-109",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 2,
    row: 6,
    column: 7,
  },
  {
    id: "object-110",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 14,
    row: 7,
    column: 7,
  },
  {
    id: "object-113",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 12,
    row: 9,
    column: 7,
  },
  {
    id: "object-114",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 0,
    row: 8,
    column: 7,
  },
  {
    id: "object-117",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 73,
    row: 8,
    column: 6,
  },
  {
    id: "object-106",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 36,
    row: 1,
    column: 15,
  },
  {
    id: "object-124",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 36,
    row: 3,
    column: 29,
  },
  {
    id: "object-125",
    layerId: "objects",
    sourceId: "signsSides",
    frame: 3,
    row: 9,
    column: 33,
  },
  {
    id: "object-107",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 37,
    row: 0,
    column: 12,
  },
  {
    id: "object-126",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 79,
    row: 7,
    column: 24,
  },
  {
    id: "object-135",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 80,
    row: 7,
    column: 25,
  },
  {
    id: "object-137",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 9,
    row: 16,
    column: 16,
  },
  {
    id: "object-138",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 9,
    row: 21,
    column: 18,
  },
  {
    id: "object-142",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 12,
    column: 15,
  },
  {
    id: "object-143",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 20,
    column: 19,
  },
  {
    id: "object-144",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 24,
    row: 19,
    column: 20,
  },
  {
    id: "object-139",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 20,
    column: 33,
  },
  {
    id: "object-145",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 15,
    column: 27,
  },
  {
    id: "object-156",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 4,
    row: 12,
    column: 24,
  },
  {
    id: "object-157",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 3,
    row: 12,
    column: 25,
  },
  {
    id: "object-158",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 24,
    row: 3,
    column: 24,
  },
  {
    id: "object-136",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 36,
    row: 4,
    column: 34,
  },
  {
    id: "object-159",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 37,
    row: 3,
    column: 33,
  },
  {
    id: "object-111",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 30,
    row: 3,
    column: 20,
  },
  {
    id: "object-112",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 30,
    row: 3,
    column: 19,
  },
  {
    id: "object-115",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 25,
    row: 3,
    column: 21,
  },
  {
    id: "object-91",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 16,
    row: 0,
    column: 8,
  },
  {
    id: "object-92",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 24,
    row: 0,
    column: 9,
  },
  {
    id: "object-93",
    layerId: "objects",
    sourceId: "barnStructures",
    frame: 0,
    row: 5,
    column: 19,
  },
  {
    id: "object-94",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 27,
    row: 10,
    column: 10,
  },
  {
    id: "object-95",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 26,
    row: 11,
    column: 11,
  },
  {
    id: "object-96",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 26,
    row: 11,
    column: 7,
  },
  {
    id: "object-97",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 48,
    row: 16,
    column: 18,
  },
  {
    id: "object-98",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 49,
    row: 17,
    column: 19,
  },
  {
    id: "object-99",
    layerId: "objects",
    sourceId: "mushroomsFlowersStones",
    frame: 15,
    row: 6,
    column: 11,
  },
  {
    id: "object-100",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 49,
    row: 6,
    column: 9,
  },
  {
    id: "object-101",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 52,
    row: 5,
    column: 10,
  },
  {
    id: "object-102",
    layerId: "objects",
    sourceId: "treesStumpsBushes",
    frame: 51,
    row: 4,
    column: 11,
  },
] as const;

export const PIXEL_FARM_GENERATED_COLLISIONS = [
  {
    id: "collision-1",
    halfTileRow: 6,
    halfTileColumn: 36,
  },
  {
    id: "collision-2",
    halfTileRow: 7,
    halfTileColumn: 36,
  },
  {
    id: "collision-3",
    halfTileRow: 8,
    halfTileColumn: 36,
  },
  {
    id: "collision-4",
    halfTileRow: 9,
    halfTileColumn: 36,
  },
  {
    id: "collision-5",
    halfTileRow: 10,
    halfTileColumn: 36,
  },
  {
    id: "collision-6",
    halfTileRow: 12,
    halfTileColumn: 36,
  },
  {
    id: "collision-7",
    halfTileRow: 11,
    halfTileColumn: 36,
  },
  {
    id: "collision-8",
    halfTileRow: 13,
    halfTileColumn: 36,
  },
  {
    id: "collision-9",
    halfTileRow: 13,
    halfTileColumn: 37,
  },
  {
    id: "collision-10",
    halfTileRow: 13,
    halfTileColumn: 38,
  },
  {
    id: "collision-11",
    halfTileRow: 13,
    halfTileColumn: 40,
  },
  {
    id: "collision-12",
    halfTileRow: 13,
    halfTileColumn: 42,
  },
  {
    id: "collision-13",
    halfTileRow: 13,
    halfTileColumn: 43,
  },
  {
    id: "collision-14",
    halfTileRow: 13,
    halfTileColumn: 39,
  },
  {
    id: "collision-15",
    halfTileRow: 13,
    halfTileColumn: 41,
  },
  {
    id: "collision-16",
    halfTileRow: 12,
    halfTileColumn: 43,
  },
  {
    id: "collision-17",
    halfTileRow: 9,
    halfTileColumn: 43,
  },
  {
    id: "collision-18",
    halfTileRow: 6,
    halfTileColumn: 37,
  },
  {
    id: "collision-19",
    halfTileRow: 6,
    halfTileColumn: 38,
  },
  {
    id: "collision-20",
    halfTileRow: 6,
    halfTileColumn: 40,
  },
  {
    id: "collision-21",
    halfTileRow: 6,
    halfTileColumn: 42,
  },
  {
    id: "collision-22",
    halfTileRow: 6,
    halfTileColumn: 41,
  },
  {
    id: "collision-23",
    halfTileRow: 6,
    halfTileColumn: 43,
  },
  {
    id: "collision-24",
    halfTileRow: 7,
    halfTileColumn: 39,
  },
  {
    id: "collision-25",
    halfTileRow: 7,
    halfTileColumn: 40,
  },
  {
    id: "collision-26",
    halfTileRow: 7,
    halfTileColumn: 43,
  },
  {
    id: "collision-27",
    halfTileRow: 8,
    halfTileColumn: 43,
  },
  {
    id: "collision-28",
    halfTileRow: 10,
    halfTileColumn: 38,
  },
  {
    id: "collision-29",
    halfTileRow: 10,
    halfTileColumn: 39,
  },
  {
    id: "collision-30",
    halfTileRow: 11,
    halfTileColumn: 39,
  },
  {
    id: "collision-31",
    halfTileRow: 11,
    halfTileColumn: 38,
  },
  {
    id: "collision-32",
    halfTileRow: 20,
    halfTileColumn: 27,
  },
  {
    id: "collision-33",
    halfTileRow: 19,
    halfTileColumn: 27,
  },
  {
    id: "collision-34",
    halfTileRow: 17,
    halfTileColumn: 27,
  },
  {
    id: "collision-35",
    halfTileRow: 18,
    halfTileColumn: 27,
  },
  {
    id: "collision-36",
    halfTileRow: 16,
    halfTileColumn: 27,
  },
  {
    id: "collision-37",
    halfTileRow: 16,
    halfTileColumn: 28,
  },
  {
    id: "collision-38",
    halfTileRow: 16,
    halfTileColumn: 30,
  },
  {
    id: "collision-39",
    halfTileRow: 16,
    halfTileColumn: 32,
  },
  {
    id: "collision-40",
    halfTileRow: 16,
    halfTileColumn: 31,
  },
  {
    id: "collision-41",
    halfTileRow: 16,
    halfTileColumn: 29,
  },
  {
    id: "collision-42",
    halfTileRow: 17,
    halfTileColumn: 28,
  },
  {
    id: "collision-43",
    halfTileRow: 17,
    halfTileColumn: 30,
  },
  {
    id: "collision-44",
    halfTileRow: 17,
    halfTileColumn: 32,
  },
  {
    id: "collision-45",
    halfTileRow: 18,
    halfTileColumn: 32,
  },
  {
    id: "collision-46",
    halfTileRow: 19,
    halfTileColumn: 32,
  },
  {
    id: "collision-47",
    halfTileRow: 20,
    halfTileColumn: 32,
  },
  {
    id: "collision-48",
    halfTileRow: 20,
    halfTileColumn: 31,
  },
  {
    id: "collision-49",
    halfTileRow: 20,
    halfTileColumn: 30,
  },
  {
    id: "collision-50",
    halfTileRow: 20,
    halfTileColumn: 29,
  },
  {
    id: "collision-51",
    halfTileRow: 20,
    halfTileColumn: 28,
  },
  {
    id: "collision-52",
    halfTileRow: 17,
    halfTileColumn: 29,
  },
  {
    id: "collision-53",
    halfTileRow: 18,
    halfTileColumn: 29,
  },
  {
    id: "collision-54",
    halfTileRow: 18,
    halfTileColumn: 30,
  },
  {
    id: "collision-55",
    halfTileRow: 17,
    halfTileColumn: 31,
  },
  {
    id: "collision-56",
    halfTileRow: 18,
    halfTileColumn: 31,
  },
  {
    id: "collision-57",
    halfTileRow: 18,
    halfTileColumn: 28,
  },
  {
    id: "collision-58",
    halfTileRow: 19,
    halfTileColumn: 28,
  },
  {
    id: "collision-59",
    halfTileRow: 19,
    halfTileColumn: 29,
  },
  {
    id: "collision-60",
    halfTileRow: 19,
    halfTileColumn: 30,
  },
  {
    id: "collision-61",
    halfTileRow: 19,
    halfTileColumn: 31,
  },
  {
    id: "collision-62",
    halfTileRow: 9,
    halfTileColumn: 48,
  },
  {
    id: "collision-63",
    halfTileRow: 8,
    halfTileColumn: 48,
  },
  {
    id: "collision-64",
    halfTileRow: 7,
    halfTileColumn: 48,
  },
  {
    id: "collision-65",
    halfTileRow: 6,
    halfTileColumn: 48,
  },
  {
    id: "collision-66",
    halfTileRow: 12,
    halfTileColumn: 48,
  },
  {
    id: "collision-67",
    halfTileRow: 13,
    halfTileColumn: 48,
  },
  {
    id: "collision-68",
    halfTileRow: 14,
    halfTileColumn: 48,
  },
  {
    id: "collision-69",
    halfTileRow: 15,
    halfTileColumn: 48,
  },
  {
    id: "collision-70",
    halfTileRow: 16,
    halfTileColumn: 48,
  },
  {
    id: "collision-71",
    halfTileRow: 17,
    halfTileColumn: 48,
  },
  {
    id: "collision-72",
    halfTileRow: 17,
    halfTileColumn: 49,
  },
  {
    id: "collision-73",
    halfTileRow: 17,
    halfTileColumn: 50,
  },
  {
    id: "collision-74",
    halfTileRow: 17,
    halfTileColumn: 51,
  },
  {
    id: "collision-75",
    halfTileRow: 17,
    halfTileColumn: 52,
  },
  {
    id: "collision-76",
    halfTileRow: 18,
    halfTileColumn: 52,
  },
  {
    id: "collision-77",
    halfTileRow: 19,
    halfTileColumn: 52,
  },
  {
    id: "collision-78",
    halfTileRow: 20,
    halfTileColumn: 52,
  },
  {
    id: "collision-79",
    halfTileRow: 21,
    halfTileColumn: 52,
  },
  {
    id: "collision-80",
    halfTileRow: 21,
    halfTileColumn: 53,
  },
  {
    id: "collision-81",
    halfTileRow: 21,
    halfTileColumn: 54,
  },
  {
    id: "collision-82",
    halfTileRow: 6,
    halfTileColumn: 49,
  },
  {
    id: "collision-83",
    halfTileRow: 6,
    halfTileColumn: 50,
  },
  {
    id: "collision-84",
    halfTileRow: 6,
    halfTileColumn: 51,
  },
  {
    id: "collision-85",
    halfTileRow: 6,
    halfTileColumn: 52,
  },
  {
    id: "collision-86",
    halfTileRow: 6,
    halfTileColumn: 53,
  },
  {
    id: "collision-87",
    halfTileRow: 6,
    halfTileColumn: 54,
  },
  {
    id: "collision-88",
    halfTileRow: 6,
    halfTileColumn: 55,
  },
  {
    id: "collision-89",
    halfTileRow: 6,
    halfTileColumn: 56,
  },
  {
    id: "collision-90",
    halfTileRow: 6,
    halfTileColumn: 57,
  },
  {
    id: "collision-91",
    halfTileRow: 6,
    halfTileColumn: 58,
  },
  {
    id: "collision-92",
    halfTileRow: 6,
    halfTileColumn: 59,
  },
  {
    id: "collision-93",
    halfTileRow: 6,
    halfTileColumn: 60,
  },
  {
    id: "collision-94",
    halfTileRow: 6,
    halfTileColumn: 61,
  },
  {
    id: "collision-95",
    halfTileRow: 6,
    halfTileColumn: 62,
  },
  {
    id: "collision-96",
    halfTileRow: 6,
    halfTileColumn: 63,
  },
  {
    id: "collision-97",
    halfTileRow: 6,
    halfTileColumn: 64,
  },
  {
    id: "collision-98",
    halfTileRow: 6,
    halfTileColumn: 66,
  },
  {
    id: "collision-99",
    halfTileRow: 6,
    halfTileColumn: 65,
  },
  {
    id: "collision-100",
    halfTileRow: 6,
    halfTileColumn: 67,
  },
  {
    id: "collision-101",
    halfTileRow: 7,
    halfTileColumn: 67,
  },
  {
    id: "collision-102",
    halfTileRow: 8,
    halfTileColumn: 67,
  },
  {
    id: "collision-103",
    halfTileRow: 8,
    halfTileColumn: 68,
  },
  {
    id: "collision-104",
    halfTileRow: 8,
    halfTileColumn: 69,
  },
  {
    id: "collision-105",
    halfTileRow: 9,
    halfTileColumn: 69,
  },
  {
    id: "collision-106",
    halfTileRow: 10,
    halfTileColumn: 69,
  },
  {
    id: "collision-107",
    halfTileRow: 11,
    halfTileColumn: 69,
  },
  {
    id: "collision-108",
    halfTileRow: 12,
    halfTileColumn: 69,
  },
  {
    id: "collision-109",
    halfTileRow: 13,
    halfTileColumn: 69,
  },
  {
    id: "collision-110",
    halfTileRow: 14,
    halfTileColumn: 69,
  },
  {
    id: "collision-111",
    halfTileRow: 15,
    halfTileColumn: 69,
  },
  {
    id: "collision-112",
    halfTileRow: 16,
    halfTileColumn: 69,
  },
  {
    id: "collision-113",
    halfTileRow: 17,
    halfTileColumn: 69,
  },
  {
    id: "collision-114",
    halfTileRow: 18,
    halfTileColumn: 69,
  },
  {
    id: "collision-115",
    halfTileRow: 19,
    halfTileColumn: 69,
  },
  {
    id: "collision-116",
    halfTileRow: 19,
    halfTileColumn: 66,
  },
  {
    id: "collision-117",
    halfTileRow: 19,
    halfTileColumn: 67,
  },
  {
    id: "collision-118",
    halfTileRow: 20,
    halfTileColumn: 69,
  },
  {
    id: "collision-119",
    halfTileRow: 21,
    halfTileColumn: 69,
  },
  {
    id: "collision-120",
    halfTileRow: 21,
    halfTileColumn: 68,
  },
  {
    id: "collision-121",
    halfTileRow: 21,
    halfTileColumn: 67,
  },
  {
    id: "collision-122",
    halfTileRow: 21,
    halfTileColumn: 66,
  },
  {
    id: "collision-123",
    halfTileRow: 21,
    halfTileColumn: 55,
  },
  {
    id: "collision-124",
    halfTileRow: 21,
    halfTileColumn: 56,
  },
  {
    id: "collision-125",
    halfTileRow: 21,
    halfTileColumn: 57,
  },
  {
    id: "collision-126",
    halfTileRow: 21,
    halfTileColumn: 58,
  },
  {
    id: "collision-127",
    halfTileRow: 21,
    halfTileColumn: 59,
  },
  {
    id: "collision-128",
    halfTileRow: 21,
    halfTileColumn: 60,
  },
  {
    id: "collision-129",
    halfTileRow: 21,
    halfTileColumn: 61,
  },
  {
    id: "collision-130",
    halfTileRow: 21,
    halfTileColumn: 62,
  },
  {
    id: "collision-131",
    halfTileRow: 21,
    halfTileColumn: 65,
  },
  {
    id: "collision-132",
    halfTileRow: 36,
    halfTileColumn: 26,
  },
  {
    id: "collision-133",
    halfTileRow: 36,
    halfTileColumn: 27,
  },
  {
    id: "collision-134",
    halfTileRow: 37,
    halfTileColumn: 26,
  },
  {
    id: "collision-135",
    halfTileRow: 37,
    halfTileColumn: 27,
  },
  {
    id: "collision-136",
    halfTileRow: 35,
    halfTileColumn: 26,
  },
  {
    id: "collision-137",
    halfTileRow: 35,
    halfTileColumn: 27,
  },
  {
    id: "collision-138",
    halfTileRow: 34,
    halfTileColumn: 26,
  },
  {
    id: "collision-139",
    halfTileRow: 34,
    halfTileColumn: 27,
  },
  {
    id: "collision-140",
    halfTileRow: 34,
    halfTileColumn: 24,
  },
  {
    id: "collision-141",
    halfTileRow: 34,
    halfTileColumn: 25,
  },
  {
    id: "collision-142",
    halfTileRow: 35,
    halfTileColumn: 24,
  },
  {
    id: "collision-143",
    halfTileRow: 35,
    halfTileColumn: 25,
  },
  {
    id: "collision-144",
    halfTileRow: 34,
    halfTileColumn: 22,
  },
  {
    id: "collision-145",
    halfTileRow: 34,
    halfTileColumn: 23,
  },
  {
    id: "collision-146",
    halfTileRow: 35,
    halfTileColumn: 22,
  },
  {
    id: "collision-147",
    halfTileRow: 35,
    halfTileColumn: 23,
  },
  {
    id: "collision-148",
    halfTileRow: 34,
    halfTileColumn: 20,
  },
  {
    id: "collision-149",
    halfTileRow: 34,
    halfTileColumn: 21,
  },
  {
    id: "collision-150",
    halfTileRow: 35,
    halfTileColumn: 20,
  },
  {
    id: "collision-151",
    halfTileRow: 35,
    halfTileColumn: 21,
  },
  {
    id: "collision-152",
    halfTileRow: 34,
    halfTileColumn: 18,
  },
  {
    id: "collision-153",
    halfTileRow: 34,
    halfTileColumn: 19,
  },
  {
    id: "collision-154",
    halfTileRow: 35,
    halfTileColumn: 18,
  },
  {
    id: "collision-155",
    halfTileRow: 35,
    halfTileColumn: 19,
  },
  {
    id: "collision-156",
    halfTileRow: 34,
    halfTileColumn: 16,
  },
  {
    id: "collision-157",
    halfTileRow: 34,
    halfTileColumn: 17,
  },
  {
    id: "collision-158",
    halfTileRow: 35,
    halfTileColumn: 16,
  },
  {
    id: "collision-159",
    halfTileRow: 35,
    halfTileColumn: 17,
  },
  {
    id: "collision-160",
    halfTileRow: 34,
    halfTileColumn: 15,
  },
  {
    id: "collision-161",
    halfTileRow: 35,
    halfTileColumn: 15,
  },
  {
    id: "collision-162",
    halfTileRow: 34,
    halfTileColumn: 14,
  },
  {
    id: "collision-163",
    halfTileRow: 35,
    halfTileColumn: 14,
  },
  {
    id: "collision-164",
    halfTileRow: 36,
    halfTileColumn: 14,
  },
  {
    id: "collision-165",
    halfTileRow: 36,
    halfTileColumn: 15,
  },
  {
    id: "collision-166",
    halfTileRow: 37,
    halfTileColumn: 14,
  },
  {
    id: "collision-167",
    halfTileRow: 37,
    halfTileColumn: 15,
  },
  {
    id: "collision-168",
    halfTileRow: 38,
    halfTileColumn: 14,
  },
  {
    id: "collision-169",
    halfTileRow: 38,
    halfTileColumn: 15,
  },
  {
    id: "collision-170",
    halfTileRow: 39,
    halfTileColumn: 14,
  },
  {
    id: "collision-171",
    halfTileRow: 39,
    halfTileColumn: 15,
  },
  {
    id: "collision-172",
    halfTileRow: 40,
    halfTileColumn: 14,
  },
  {
    id: "collision-173",
    halfTileRow: 40,
    halfTileColumn: 15,
  },
  {
    id: "collision-174",
    halfTileRow: 41,
    halfTileColumn: 14,
  },
  {
    id: "collision-175",
    halfTileRow: 41,
    halfTileColumn: 15,
  },
  {
    id: "collision-176",
    halfTileRow: 42,
    halfTileColumn: 14,
  },
  {
    id: "collision-177",
    halfTileRow: 42,
    halfTileColumn: 15,
  },
  {
    id: "collision-178",
    halfTileRow: 43,
    halfTileColumn: 14,
  },
  {
    id: "collision-179",
    halfTileRow: 43,
    halfTileColumn: 15,
  },
  {
    id: "collision-180",
    halfTileRow: 42,
    halfTileColumn: 17,
  },
  {
    id: "collision-182",
    halfTileRow: 43,
    halfTileColumn: 17,
  },
  {
    id: "collision-184",
    halfTileRow: 42,
    halfTileColumn: 16,
  },
  {
    id: "collision-185",
    halfTileRow: 43,
    halfTileColumn: 16,
  },
  {
    id: "collision-186",
    halfTileRow: 44,
    halfTileColumn: 16,
  },
  {
    id: "collision-187",
    halfTileRow: 44,
    halfTileColumn: 17,
  },
  {
    id: "collision-188",
    halfTileRow: 45,
    halfTileColumn: 16,
  },
  {
    id: "collision-189",
    halfTileRow: 45,
    halfTileColumn: 17,
  },
  {
    id: "collision-190",
    halfTileRow: 44,
    halfTileColumn: 18,
  },
  {
    id: "collision-191",
    halfTileRow: 44,
    halfTileColumn: 19,
  },
  {
    id: "collision-192",
    halfTileRow: 45,
    halfTileColumn: 18,
  },
  {
    id: "collision-193",
    halfTileRow: 45,
    halfTileColumn: 19,
  },
  {
    id: "collision-194",
    halfTileRow: 44,
    halfTileColumn: 20,
  },
  {
    id: "collision-195",
    halfTileRow: 44,
    halfTileColumn: 21,
  },
  {
    id: "collision-196",
    halfTileRow: 45,
    halfTileColumn: 20,
  },
  {
    id: "collision-197",
    halfTileRow: 45,
    halfTileColumn: 21,
  },
  {
    id: "collision-198",
    halfTileRow: 44,
    halfTileColumn: 22,
  },
  {
    id: "collision-199",
    halfTileRow: 44,
    halfTileColumn: 23,
  },
  {
    id: "collision-200",
    halfTileRow: 45,
    halfTileColumn: 22,
  },
  {
    id: "collision-201",
    halfTileRow: 45,
    halfTileColumn: 23,
  },
  {
    id: "collision-202",
    halfTileRow: 44,
    halfTileColumn: 24,
  },
  {
    id: "collision-203",
    halfTileRow: 44,
    halfTileColumn: 25,
  },
  {
    id: "collision-204",
    halfTileRow: 45,
    halfTileColumn: 24,
  },
  {
    id: "collision-205",
    halfTileRow: 45,
    halfTileColumn: 25,
  },
  {
    id: "collision-206",
    halfTileRow: 44,
    halfTileColumn: 26,
  },
  {
    id: "collision-207",
    halfTileRow: 44,
    halfTileColumn: 27,
  },
  {
    id: "collision-208",
    halfTileRow: 45,
    halfTileColumn: 26,
  },
  {
    id: "collision-209",
    halfTileRow: 45,
    halfTileColumn: 27,
  },
  {
    id: "collision-210",
    halfTileRow: 42,
    halfTileColumn: 26,
  },
  {
    id: "collision-211",
    halfTileRow: 42,
    halfTileColumn: 27,
  },
  {
    id: "collision-212",
    halfTileRow: 43,
    halfTileColumn: 26,
  },
  {
    id: "collision-213",
    halfTileRow: 43,
    halfTileColumn: 27,
  },
  {
    id: "collision-214",
    halfTileRow: 42,
    halfTileColumn: 28,
  },
  {
    id: "collision-215",
    halfTileRow: 42,
    halfTileColumn: 29,
  },
  {
    id: "collision-216",
    halfTileRow: 43,
    halfTileColumn: 28,
  },
  {
    id: "collision-217",
    halfTileRow: 43,
    halfTileColumn: 29,
  },
  {
    id: "collision-218",
    halfTileRow: 44,
    halfTileColumn: 30,
  },
  {
    id: "collision-219",
    halfTileRow: 44,
    halfTileColumn: 31,
  },
  {
    id: "collision-220",
    halfTileRow: 45,
    halfTileColumn: 30,
  },
  {
    id: "collision-221",
    halfTileRow: 45,
    halfTileColumn: 31,
  },
  {
    id: "collision-222",
    halfTileRow: 44,
    halfTileColumn: 32,
  },
  {
    id: "collision-223",
    halfTileRow: 44,
    halfTileColumn: 33,
  },
  {
    id: "collision-224",
    halfTileRow: 45,
    halfTileColumn: 32,
  },
  {
    id: "collision-225",
    halfTileRow: 45,
    halfTileColumn: 33,
  },
  {
    id: "collision-226",
    halfTileRow: 43,
    halfTileColumn: 11,
  },
  {
    id: "collision-227",
    halfTileRow: 43,
    halfTileColumn: 12,
  },
  {
    id: "collision-228",
    halfTileRow: 39,
    halfTileColumn: 10,
  },
  {
    id: "collision-229",
    halfTileRow: 39,
    halfTileColumn: 11,
  },
  {
    id: "collision-230",
    halfTileRow: 46,
    halfTileColumn: 38,
  },
  {
    id: "collision-231",
    halfTileRow: 47,
    halfTileColumn: 38,
  },
  {
    id: "collision-232",
    halfTileRow: 46,
    halfTileColumn: 39,
  },
  {
    id: "collision-233",
    halfTileRow: 46,
    halfTileColumn: 40,
  },
  {
    id: "collision-234",
    halfTileRow: 46,
    halfTileColumn: 41,
  },
  {
    id: "collision-235",
    halfTileRow: 46,
    halfTileColumn: 42,
  },
  {
    id: "collision-236",
    halfTileRow: 46,
    halfTileColumn: 43,
  },
  {
    id: "collision-237",
    halfTileRow: 47,
    halfTileColumn: 43,
  },
  {
    id: "collision-238",
    halfTileRow: 47,
    halfTileColumn: 41,
  },
  {
    id: "collision-239",
    halfTileRow: 47,
    halfTileColumn: 39,
  },
  {
    id: "collision-240",
    halfTileRow: 47,
    halfTileColumn: 40,
  },
  {
    id: "collision-241",
    halfTileRow: 47,
    halfTileColumn: 42,
  },
  {
    id: "collision-242",
    halfTileRow: 31,
    halfTileColumn: 20,
  },
  {
    id: "collision-243",
    halfTileRow: 31,
    halfTileColumn: 21,
  },
  {
    id: "collision-244",
    halfTileRow: 30,
    halfTileColumn: 20,
  },
  {
    id: "collision-245",
    halfTileRow: 30,
    halfTileColumn: 21,
  },
  {
    id: "collision-246",
    halfTileRow: 23,
    halfTileColumn: 13,
  },
  {
    id: "collision-247",
    halfTileRow: 23,
    halfTileColumn: 14,
  },
  {
    id: "collision-248",
    halfTileRow: 21,
    halfTileColumn: 21,
  },
  {
    id: "collision-249",
    halfTileRow: 21,
    halfTileColumn: 22,
  },
  {
    id: "collision-250",
    halfTileRow: 19,
    halfTileColumn: 14,
  },
  {
    id: "collision-251",
    halfTileRow: 19,
    halfTileColumn: 15,
  },
  {
    id: "collision-252",
    halfTileRow: 15,
    halfTileColumn: 13,
  },
  {
    id: "collision-253",
    halfTileRow: 15,
    halfTileColumn: 14,
  },
  {
    id: "collision-254",
    halfTileRow: 3,
    halfTileColumn: 27,
  },
  {
    id: "collision-255",
    halfTileRow: 3,
    halfTileColumn: 28,
  },
  {
    id: "collision-256",
    halfTileRow: 1,
    halfTileColumn: 24,
  },
  {
    id: "collision-257",
    halfTileRow: 0,
    halfTileColumn: 24,
  },
  {
    id: "collision-258",
    halfTileRow: 0,
    halfTileColumn: 25,
  },
  {
    id: "collision-259",
    halfTileRow: 1,
    halfTileColumn: 25,
  },
  {
    id: "collision-260",
    halfTileRow: 30,
    halfTileColumn: 68,
  },
  {
    id: "collision-261",
    halfTileRow: 30,
    halfTileColumn: 69,
  },
  {
    id: "collision-262",
    halfTileRow: 31,
    halfTileColumn: 68,
  },
  {
    id: "collision-263",
    halfTileRow: 31,
    halfTileColumn: 69,
  },
  {
    id: "collision-264",
    halfTileRow: 32,
    halfTileColumn: 68,
  },
  {
    id: "collision-265",
    halfTileRow: 32,
    halfTileColumn: 69,
  },
  {
    id: "collision-266",
    halfTileRow: 33,
    halfTileColumn: 68,
  },
  {
    id: "collision-267",
    halfTileRow: 33,
    halfTileColumn: 69,
  },
  {
    id: "collision-268",
    halfTileRow: 42,
    halfTileColumn: 68,
  },
  {
    id: "collision-269",
    halfTileRow: 42,
    halfTileColumn: 69,
  },
  {
    id: "collision-270",
    halfTileRow: 43,
    halfTileColumn: 68,
  },
  {
    id: "collision-271",
    halfTileRow: 43,
    halfTileColumn: 69,
  },
  {
    id: "collision-272",
    halfTileRow: 44,
    halfTileColumn: 68,
  },
  {
    id: "collision-273",
    halfTileRow: 44,
    halfTileColumn: 69,
  },
  {
    id: "collision-274",
    halfTileRow: 45,
    halfTileColumn: 68,
  },
  {
    id: "collision-275",
    halfTileRow: 45,
    halfTileColumn: 69,
  },
  {
    id: "collision-276",
    halfTileRow: 46,
    halfTileColumn: 66,
  },
  {
    id: "collision-277",
    halfTileRow: 46,
    halfTileColumn: 67,
  },
  {
    id: "collision-278",
    halfTileRow: 47,
    halfTileColumn: 66,
  },
  {
    id: "collision-279",
    halfTileRow: 47,
    halfTileColumn: 67,
  },
  {
    id: "collision-280",
    halfTileRow: 46,
    halfTileColumn: 64,
  },
  {
    id: "collision-281",
    halfTileRow: 46,
    halfTileColumn: 65,
  },
  {
    id: "collision-282",
    halfTileRow: 47,
    halfTileColumn: 64,
  },
  {
    id: "collision-283",
    halfTileRow: 47,
    halfTileColumn: 65,
  },
  {
    id: "collision-284",
    halfTileRow: 46,
    halfTileColumn: 62,
  },
  {
    id: "collision-285",
    halfTileRow: 46,
    halfTileColumn: 63,
  },
  {
    id: "collision-286",
    halfTileRow: 47,
    halfTileColumn: 62,
  },
  {
    id: "collision-287",
    halfTileRow: 47,
    halfTileColumn: 63,
  },
  {
    id: "collision-288",
    halfTileRow: 46,
    halfTileColumn: 52,
  },
  {
    id: "collision-289",
    halfTileRow: 46,
    halfTileColumn: 53,
  },
  {
    id: "collision-290",
    halfTileRow: 47,
    halfTileColumn: 52,
  },
  {
    id: "collision-291",
    halfTileRow: 47,
    halfTileColumn: 53,
  },
  {
    id: "collision-292",
    halfTileRow: 46,
    halfTileColumn: 50,
  },
  {
    id: "collision-293",
    halfTileRow: 46,
    halfTileColumn: 51,
  },
  {
    id: "collision-294",
    halfTileRow: 47,
    halfTileColumn: 50,
  },
  {
    id: "collision-295",
    halfTileRow: 47,
    halfTileColumn: 51,
  },
  {
    id: "collision-296",
    halfTileRow: 46,
    halfTileColumn: 48,
  },
  {
    id: "collision-297",
    halfTileRow: 46,
    halfTileColumn: 49,
  },
  {
    id: "collision-298",
    halfTileRow: 47,
    halfTileColumn: 48,
  },
  {
    id: "collision-299",
    halfTileRow: 47,
    halfTileColumn: 49,
  },
  {
    id: "collision-300",
    halfTileRow: 28,
    halfTileColumn: 61,
  },
  {
    id: "collision-301",
    halfTileRow: 28,
    halfTileColumn: 62,
  },
  {
    id: "collision-302",
    halfTileRow: 29,
    halfTileColumn: 61,
  },
  {
    id: "collision-303",
    halfTileRow: 29,
    halfTileColumn: 62,
  },
  {
    id: "collision-304",
    halfTileRow: 8,
    halfTileColumn: 62,
  },
  {
    id: "collision-305",
    halfTileRow: 8,
    halfTileColumn: 63,
  },
  {
    id: "collision-306",
    halfTileRow: 9,
    halfTileColumn: 62,
  },
  {
    id: "collision-307",
    halfTileRow: 9,
    halfTileColumn: 63,
  },
  {
    id: "collision-308",
    halfTileRow: 8,
    halfTileColumn: 61,
  },
  {
    id: "collision-309",
    halfTileRow: 9,
    halfTileColumn: 61,
  },
  {
    id: "collision-310",
    halfTileRow: 9,
    halfTileColumn: 64,
  },
  {
    id: "collision-311",
    halfTileRow: 8,
    halfTileColumn: 64,
  },
  {
    id: "collision-312",
    halfTileRow: 7,
    halfTileColumn: 64,
  },
  {
    id: "collision-313",
    halfTileRow: 7,
    halfTileColumn: 63,
  },
  {
    id: "collision-314",
    halfTileRow: 7,
    halfTileColumn: 62,
  },
  {
    id: "collision-315",
    halfTileRow: 7,
    halfTileColumn: 61,
  },
] as const;
