export const REPORT_PDF_STORAGE_KEY = "mem9.reportPdfPayload";

export interface ReportPdfTopicBlock {
  title: string;
  tags: string[];
  description: string;
  evidence: string;
  share: string;
}

export interface ReportPdfEvidenceItem {
  id: string;
  text: string;
  confidence: number;
}

export interface ReportPdfPayload {
  brand: string;
  badge: string;
  title: string;
  subtitle: string;
  summary: {
    eyebrow: string;
    title: string;
    body: string;
    recommendation: string;
  };
  before: ReportPdfTopicBlock;
  after: ReportPdfTopicBlock;
  explanation: {
    title: string;
    paragraphs: string[];
    confidence: number;
  };
  evidenceTitle: string;
  evidence: ReportPdfEvidenceItem[];
  footer: {
    generatedBy: string;
    template: string;
    reportId: string;
    page: string;
  };
}

export function buildTemplateReportPdfPayload({
  templateName,
  goal,
  templateId,
  reportIndex,
}: {
  templateName: string;
  goal: string;
  templateId: string;
  reportIndex: number;
}): ReportPdfPayload {
  const reportId = `rpt_focus_20250614_${String(reportIndex + 1).padStart(3, "0")}`;

  return {
    brand: "MEM9 Your Memory",
    badge: "PDF 报告",
    title: `${templateName}报告`,
    subtitle: `${goal}，并提供变化结论、证据与置信度。`,
    summary: {
      eyebrow: "EXECUTIVE SUMMARY",
      title: "本期关注点从“饮食控制 / 体重管理”扩展到“KET 备考 / 学习计划 / 健康习惯”。",
      body: "用户仍保留健康管理主题，但最近两周学习相关记忆频次显著上升，KET 备考成为更强的即时关注点。",
      recommendation: "建议：后续 Agent 在召回时优先结合学习计划与健康习惯，不再只围绕减脂目标组织陪伴策略。",
    },
    before: {
      title: "历史主要关注",
      tags: ["饮食控制", "体重管理", "步数目标"],
      description: "历史记忆中，用户多次提到饮食约束、减重目标和步数管理。",
      evidence: "代表证据：mem_0872、mem_0906、mem_1018",
      share: "主题占比：健康 / 饮食相关 52%",
    },
    after: {
      title: "本期主要关注",
      tags: ["KET 备考", "学习计划", "健康习惯"],
      description: "本期新增多条学习计划与 KET 相关记忆，健康主题转为支撑性背景。",
      evidence: "代表证据：mem_1021、mem_1034、mem_1088",
      share: "主题占比：学习相关 48%，健康相关 35%",
    },
    explanation: {
      title: "变化解释",
      paragraphs: [
        "学习相关关注上升主要来自 KET 备考计划、单词复习安排和备考陪伴需求。",
        "健康主题未消失，而是从“目标本身”转为“执行约束与生活习惯背景”，与学习计划共同构成用户当前关注。",
      ],
      confidence: 91,
    },
    evidenceTitle: "关键证据",
    evidence: [
      { id: "mem_1021", text: "用户最近多次提到 KET 备考计划。", confidence: 94 },
      { id: "mem_1034", text: "单词计划与复习节奏成为高频主题。", confidence: 82 },
      { id: "mem_0872", text: "步数目标和健康习惯仍作为背景约束。", confidence: 91 },
    ],
    footer: {
      generatedBy: "Generated by mem9 Your Memory",
      template: `${templateId}_v1`,
      reportId,
      page: "Page 1 / 1",
    },
  };
}
